window.KENNEY_KITS = [
 {
  "slug": "ken-survival",
  "name": "ken-survival",
  "url": "https://kenney.nl/assets/survival-kit",
  "models": [
   "bedroll",
   "bedroll-frame",
   "bedroll-packed",
   "bottle",
   "bottle-large",
   "box-large-open",
   "campfire-fishing-stand",
   "campfire-pit",
   "campfire-stand",
   "chest",
   "fence",
   "fence-doorway",
   "fence-fortified",
   "fish",
   "fish-large",
   "floor",
   "floor-hole",
   "floor-old",
   "resource-planks",
   "resource-stone",
   "resource-stone-large",
   "rock-a",
   "rock-b",
   "rock-c",
   "rock-flat",
   "rock-flat-grass",
   "rock-sand-a",
   "rock-sand-b",
   "rock-sand-c",
   "signpost",
   "signpost-single",
   "structure",
   "structure-canvas",
   "structure-floor",
   "structure-roof",
   "tent",
   "tent-canvas",
   "tool-axe",
   "tool-hammer",
   "tool-hoe",
   "tool-pickaxe",
   "tool-shovel",
   "tree",
   "tree-log",
   "tree-log-small",
   "tree-tall",
   "workbench",
   "workbench-anvil",
   "workbench-grind"
  ]
 },
 {
  "slug": "ken-pirate",
  "name": "ken-pirate",
  "url": "https://kenney.nl/assets/pirate-kit",
  "models": [
   "barrel",
   "boat-row-large",
   "boat-row-small",
   "bottle",
   "bottle-large",
   "cannon",
   "cannon-ball",
   "cannon-mobile",
   "chest",
   "crate",
   "crate-bottles",
   "flag",
   "flag-high",
   "hole",
   "mast",
   "mast-ropes",
   "palm-bend",
   "palm-detailed-bend",
   "palm-detailed-straight",
   "patch-grass",
   "patch-grass-foliage",
   "patch-sand",
   "patch-sand-foliage",
   "platform",
   "platform-planks",
   "rocks-a",
   "rocks-b",
   "rocks-c",
   "rocks-sand-a",
   "rocks-sand-b",
   "rocks-sand-c",
   "ship-ghost",
   "ship-large",
   "ship-medium",
   "ship-pirate-large",
   "ship-pirate-medium",
   "ship-pirate-small",
   "ship-small",
   "ship-wreck",
   "structure",
   "structure-fence",
   "structure-fence-sides",
   "structure-platform",
   "structure-platform-dock",
   "structure-platform-dock-small",
   "structure-platform-small",
   "structure-roof",
   "tool-paddle",
   "tool-shovel"
  ]
 },
 {
  "slug": "ken-cave",
  "name": "ken-cave",
  "url": "https://kenney.nl/assets/modular-cave-kit",
  "ownPalette": true,
  "outsideCatalog": [
   "corridor", "corridor-corner", "corridor-end", "corridor-intersection", "corridor-junction",
   "corridor-transition", "corridor-wide", "corridor-wide-corner", "corridor-wide-end",
   "corridor-wide-intersection", "corridor-wide-junction", "gate", "gate-metal-bars",
   "gate-overhang", "gate-rock", "room-corner", "room-large", "room-large-variation",
   "room-small", "room-small-variation", "room-wide", "room-wide-variation", "stairs",
   "stairs-wide", "template-corner", "template-detail", "template-floor", "template-floor-big",
   "template-floor-detail", "template-floor-detail-a", "template-wall", "template-wall-corner",
   "template-wall-detail-a", "template-wall-half", "template-wall-stairs", "template-wall-top"
  ],
  "models": [
   "corridor",
   "corridor-corner",
   "corridor-end",
   "corridor-intersection",
   "corridor-junction",
   "corridor-transition",
   "corridor-wide",
   "corridor-wide-corner",
   "corridor-wide-end",
   "corridor-wide-intersection",
   "corridor-wide-junction",
   "gate",
   "gate-metal-bars",
   "gate-overhang",
   "gate-rock",
   "ladder",
   "room-corner",
   "room-large",
   "room-large-variation",
   "room-small",
   "room-small-variation",
   "room-wide",
   "room-wide-variation",
   "stairs",
   "stairs-wide",
   "template-corner",
   "template-detail",
   "template-floor",
   "template-floor-big",
   "template-floor-detail",
   "template-floor-detail-a",
   "template-floor-layer",
   "template-floor-layer-hole",
   "template-floor-layer-raised",
   "template-wall",
   "template-wall-corner",
   "template-wall-detail-a",
   "template-wall-half",
   "template-wall-stairs",
   "template-wall-top"
  ]
 },
 {
  "slug": "ken-forest-mini",
  "name": "ken-forest-mini",
  "url": "https://kenney.nl/assets/mini-forest",
  "models": [
   "bridge",
   "building-roof",
   "building-structure",
   "ladder",
   "patch-dirt",
   "patch-grass",
   "stones",
   "target",
   "tent",
   "tree",
   "tree-high"
  ]
 },
 {
  "slug": "ken-town",
  "name": "ken-town",
  "url": "https://kenney.nl/assets/fantasy-town-kit",
  "models": [
   "balcony-wall",
   "balcony-wall-fence",
   "banner-green",
   "banner-red",
   "blade",
   "cart",
   "cart-high",
   "chimney",
   "fence",
   "fence-broken",
   "fence-curved",
   "fence-gate",
   "fountain-square-detail",
   "overhang",
   "pillar-wood",
   "planks",
   "planks-half",
   "planks-opening",
   "poles",
   "poles-horizontal",
   "rock-large",
   "rock-small",
   "rock-wide",
   "roof-corner",
   "roof-corner-inner",
   "roof-corner-round",
   "roof-flat",
   "roof-gable-detail",
   "roof-gable-end",
   "roof-gable-top",
   "roof-left",
   "roof-point",
   "roof-right",
   "roof-window",
   "stairs-stone-corner",
   "stairs-stone-round",
   "stairs-wide-wood",
   "stairs-wide-wood-handrail",
   "stairs-wood",
   "stairs-wood-handrail",
   "tree",
   "tree-crooked",
   "tree-high",
   "tree-high-crooked",
   "tree-high-round",
   "wall-wood",
   "wall-wood-arch",
   "wall-wood-arch-top",
   "wall-wood-block",
   "wall-wood-block-half",
   "wall-wood-broken",
   "wall-wood-corner",
   "wall-wood-corner-diagonal",
   "wall-wood-corner-diagonal-half",
   "wall-wood-corner-edge",
   "wall-wood-curved",
   "wall-wood-detail-cross",
   "wall-wood-detail-diagonal",
   "wall-wood-detail-horizontal",
   "wall-wood-diagonal",
   "wall-wood-door",
   "wall-wood-doorway-base",
   "wall-wood-doorway-square",
   "wall-wood-doorway-square-wide-curved",
   "wall-wood-half",
   "wall-wood-side",
   "wall-wood-window-glass",
   "wall-wood-window-round",
   "wall-wood-window-shutters",
   "watermill",
   "watermill-wide",
   "wheel",
   "windmill"
  ]
 },
 {
  "slug": "ken-platformer",
  "name": "ken-platformer",
  "url": "https://kenney.nl/assets/platformer-kit",
  "models": [
   "arrow",
   "arrows",
   "chest",
   "coin-gold",
   "crate",
   "crate-strong",
   "door",
   "fence-broken",
   "fence-corner",
   "fence-corner-curved",
   "fence-low-broken",
   "fence-low-corner",
   "fence-low-corner-curved",
   "fence-low-straight",
   "fence-rope",
   "fence-straight",
   "flowers",
   "flowers-tall",
   "heart",
   "ladder",
   "ladder-broken",
   "ladder-long",
   "lever",
   "lock",
   "mushrooms",
   "platform",
   "platform-fortified",
   "platform-overhang",
   "platform-ramp",
   "rocks",
   "sign",
   "spring",
   "star",
   "stones",
   "tree",
   "tree-pine-small"
  ]
 },
 {
  "slug": "quat-ocean",
  "name": "quat-ocean",
  "url": "https://quaternius.com/",
  "outsideCatalog": true,
  "models": [
   "coral-a",
   "coral-b",
   "coral-c",
   "coral-d",
   "coral-e",
   "coral-f",
   "coral-g",
   "crab",
   "dolphin",
   "eel",
   "fish-brown",
   "fish-clown",
   "fish-dory",
   "fish-tuna",
   "lobster",
   "octopus",
   "orca",
   "orca-calf",
   "penguin",
   "rock-a",
   "rock-b",
   "rock-c",
   "rock-d",
   "rock-e",
   "rock-f",
   "rock-g",
   "rock-h",
   "rock-i",
   "rock-j",
   "rock-k",
   "sand-dollar",
   "seal",
   "seaweed-a",
   "seaweed-b",
   "seaweed-c",
   "shark",
   "shark-hammerhead",
   "shell-clam",
   "shell-scallop",
   "shell-spiral",
   "squid",
   "starfish",
   "stingray",
   "turtle",
   "whale"
  ]
 },
 {
  "slug": "taalei-kit",
  "name": "taalei-kit",
  "url": null,
  "models": [
   "balloon",
   "lighthouse"
  ]
 },
 {
  "slug": "props",
  "name": "props",
  "url": null,
  "models": [
   "axe-a",
   "bag-a",
   "barrel-a",
   "bench-a",
   "bottle-a",
   "bottle-b",
   "bottle-c",
   "box-a",
   "bucket-a",
   "candle-a",
   "carpet-a",
   "coin-a",
   "coin-b",
   "coin-c",
   "cup-a",
   "cup-b",
   "fire-a",
   "firewood-a",
   "jug-a",
   "jug-b",
   "jug-c",
   "jug-d",
   "mushroom-a",
   "plate-b",
   "plate-c",
   "roast-a",
   "stairs-a",
   "stool-a",
   "table-a"
  ]
 },
 {
  "slug": "rocks",
  "name": "rocks",
  "url": null,
  "models": [
   "debris-a",
   "debris-b",
   "pebbles-dirt-a",
   "pebbles-dirt-b",
   "pebbles-dirt-c",
   "pebbles-dirt-d",
   "rock-natural-a",
   "rock-natural-b",
   "rock-natural-c",
   "rock-natural-d",
   "rock-natural-e",
   "rock-natural-f",
   "rock-natural-g",
   "rock-natural-h",
   "rock-natural-i",
   "rock-natural-j",
   "rockform-arch",
   "rockform-column",
   "rockform-corner-hard",
   "rockform-corner-soft",
   "rockform-wall-long",
   "rockform-wall-short-a",
   "rockform-wall-short-b",
   "rockwall-corner",
   "rockwall-straight"
  ]
 },
 {
  "slug": "fs-town",
  "name": "fs-town",
  "url": null,
  "models": [
   "barrel-a",
   "barrel-a-open",
   "barrel-b",
   "bell-a",
   "boat-a",
   "boat-b",
   "boat-oars-a",
   "boat-oars-b",
   "canopy-beam",
   "canopy-beam-short",
   "canopy-corner",
   "canopy-full",
   "canopy-ramp-corner",
   "canopy-ramp-full",
   "canopy-ramp-mid",
   "canopy-side",
   "canopy-sides-opposite",
   "canopy-top",
   "cart-a",
   "cart-a-barrels",
   "chimney-pipe",
   "cobblestone-dirt-transition-a",
   "cobblestone-dirt-transition-b",
   "cobblestone-dirt-transition-c",
   "cobblestone-dirt-transition-d",
   "cobblestone-floor-a",
   "crate-a",
   "crate-a-open",
   "dirt-fading",
   "dirt-fading-gathered",
   "dirt-gathered-corner",
   "dirt-gathered-straight",
   "door-ornate",
   "door-simple",
   "ladder-a",
   "lamp-street",
   "lamp-wall",
   "roof-accent-rake-concave",
   "roof-accent-rake-convex",
   "roof-accent-rake-eave",
   "roof-accent-rake-straight",
   "roof-accent-ridge",
   "roof-accent-ridge-end",
   "roof-concave-corner-inner",
   "roof-concave-corner-outer",
   "roof-concave-corner-outer-eave",
   "roof-concave-side",
   "roof-concave-side-eave",
   "roof-concave-side-eave-edge",
   "roof-concave-side-edge",
   "roof-convex-corner-inner",
   "roof-convex-corner-outer",
   "roof-convex-corner-outer-eave",
   "roof-convex-side",
   "roof-convex-side-eave",
   "roof-convex-side-eave-edge",
   "roof-convex-side-edge",
   "roof-straight-corner-inner",
   "roof-straight-corner-outer",
   "roof-straight-corner-outer-eave",
   "roof-straight-side",
   "roof-straight-side-eave",
   "roof-straight-side-eave-edge",
   "roof-straight-side-edge",
   "sign-a",
   "stone-arch",
   "stone-curb-a",
   "stone-curb-b",
   "stone-curb-c",
   "stone-curb-d",
   "stone-doorway-narrow-tall-a",
   "stone-doorway-narrow-tall-b",
   "stone-doorway-wide-tall-a",
   "stone-doorway-wide-tall-b",
   "stone-stucco-doorway-wide-tall-a",
   "stone-stucco-doorway-wide-tall-b",
   "stone-wall-a",
   "stone-wall-b",
   "stone-wall-c",
   "stone-wall-d",
   "stone-wall-e",
   "stucco-arch-half",
   "stucco-arch-half-outer",
   "stucco-block",
   "stucco-doorway-narrow-tall",
   "stucco-doorway-wide-tall",
   "stucco-support-angled-large",
   "stucco-support-angled-low",
   "stucco-support-angled-small",
   "stucco-support-beam-a",
   "stucco-support-beam-b",
   "stucco-support-beam-c",
   "stucco-support-pillar-a",
   "stucco-support-pillar-b",
   "stucco-support-pillar-c",
   "stucco-window-double-narrow",
   "stucco-window-double-narrow-tall",
   "stucco-window-double-wide",
   "stucco-window-double-wide-tall",
   "stucco-window-rounded-narrow",
   "stucco-window-rounded-narrow-tall",
   "stucco-window-rounded-wide",
   "stucco-window-rounded-wide-tall",
   "stucco-window-single-narrow",
   "stucco-window-single-narrow-tall",
   "stucco-window-single-wide",
   "stucco-window-single-wide-tall",
   "waterwheel",
   "waterwheel-flume-brace",
   "waterwheel-flume-brace-double",
   "waterwheel-flume-end",
   "waterwheel-flume-pillar",
   "waterwheel-flume-ramp",
   "waterwheel-flume-ramp-supported",
   "waterwheel-flume-straight",
   "well-a",
   "well-base-cobblestone",
   "well-base-dirt",
   "well-base-grass",
   "well-inside",
   "windmill-blades",
   "window-upper-straight",
   "wood-baseboard",
   "wood-floor-corner",
   "wood-floor-straight-a",
   "wood-floor-straight-b",
   "wood-floor-straight-c",
   "wood-floor-straight-d",
   "wood-post-large",
   "wood-post-small",
   "wood-railing-corner",
   "wood-railing-stairs",
   "wood-railing-straight",
   "wood-rope-corner",
   "wood-rope-stairs",
   "wood-rope-straight",
   "wood-steps",
   "wood-steps-stucco"
  ]
 },
 {
  "slug": "kay-tools",
  "name": "kay-tools",
  "url": "https://www.kaylousberg.com",
  "models": [
   "anvil",
   "axe",
   "blueprint",
   "blueprint-stacked",
   "bucket-metal",
   "chisel",
   "compass-base",
   "drafting-compass",
   "file",
   "grindstone",
   "hammer",
   "handdrill",
   "handplane",
   "journal-closed",
   "journal-open",
   "knife",
   "lantern",
   "magnifying-glass",
   "mallet",
   "map",
   "map-empty",
   "map-rolled",
   "nail",
   "pencil-a-long",
   "pencil-b-long",
   "pickaxe",
   "rope-bundle-a",
   "rope-bundle-b",
   "saw",
   "scissors",
   "screw-b",
   "screwdriver-a-short",
   "screwdriver-b-short",
   "shovel",
   "tongs",
   "torch",
   "torch-burnt",
   "trowel",
   "wrench-b"
  ]
 },
 {
  "slug": "kay-forest",
  "name": "kay-forest",
  "url": "https://www.kaylousberg.com",
  "models": [
   "grass-1-a",
   "grass-1-b",
   "grass-1-c",
   "grass-1-d",
   "grass-1-d-singlesided",
   "grass-2-a",
   "grass-2-b",
   "grass-2-c",
   "grass-2-d",
   "grass-2-d-singlesided",
   "rock-1-a",
   "rock-1-b",
   "rock-1-c",
   "rock-1-d",
   "rock-1-e",
   "rock-1-f",
   "rock-1-g",
   "rock-1-h",
   "rock-1-i",
   "rock-1-j",
   "rock-1-k",
   "rock-1-l",
   "rock-1-m",
   "rock-1-n",
   "rock-1-o",
   "rock-1-p",
   "rock-1-q",
   "rock-2-a",
   "rock-2-b",
   "rock-2-c",
   "rock-2-d",
   "rock-2-e",
   "rock-2-f",
   "rock-2-g",
   "rock-2-h",
   "rock-3-a",
   "rock-3-b",
   "rock-3-c",
   "rock-3-d",
   "rock-3-e",
   "rock-3-f",
   "rock-3-g",
   "rock-3-h",
   "rock-3-i",
   "rock-3-j",
   "rock-3-k",
   "rock-3-l",
   "rock-3-m",
   "rock-3-n",
   "rock-3-o",
   "rock-3-p",
   "rock-3-q",
   "rock-3-r",
   "tree-bare-1-a",
   "tree-bare-1-b",
   "tree-bare-1-c",
   "tree-bare-2-a",
   "tree-bare-2-b",
   "tree-bare-2-c"
  ]
 },
 {
  "slug": "kay-resources",
  "name": "kay-resources",
  "url": "https://www.kaylousberg.com",
  "models": [
   "copper-bar",
   "copper-bars",
   "copper-bars-stack-large",
   "copper-bars-stack-medium",
   "copper-bars-stack-small",
   "copper-nugget-large",
   "copper-nugget-medium",
   "copper-nugget-small",
   "copper-nuggets",
   "gold-bar",
   "gold-bars",
   "gold-bars-stack-large",
   "gold-bars-stack-medium",
   "gold-bars-stack-small",
   "gold-nugget-large",
   "gold-nugget-medium",
   "gold-nugget-small",
   "gold-nuggets",
   "iron-bar",
   "iron-bars",
   "iron-bars-stack-large",
   "iron-bars-stack-medium",
   "iron-bars-stack-small",
   "iron-nugget-large",
   "iron-nugget-medium",
   "iron-nugget-small",
   "iron-nuggets",
   "pallet-wood",
   "parts-cog",
   "parts-pile-large",
   "parts-pile-medium",
   "parts-pile-small",
   "silver-bar",
   "silver-bars",
   "silver-bars-stack-large",
   "silver-bars-stack-medium",
   "silver-bars-stack-small",
   "silver-nugget-large",
   "silver-nugget-medium",
   "silver-nugget-small",
   "silver-nuggets",
   "stone-brick",
   "stone-bricks-stack-large",
   "stone-bricks-stack-medium",
   "stone-bricks-stack-small",
   "stone-chunks-large",
   "stone-chunks-small",
   "textiles-a",
   "textiles-b",
   "textiles-stack-large",
   "textiles-stack-small",
   "wood-log-a",
   "wood-log-b",
   "wood-log-stack",
   "wood-plank-a",
   "wood-plank-b",
   "wood-plank-c",
   "wood-planks-stack-large",
   "wood-planks-stack-medium",
   "wood-planks-stack-small"
  ]
 },
 {
 "slug": "kay-dun-1",
 "name": "kay-dun-1",
 "url": "https://www.kaylousberg.com",
 "models": [
  "arrow",
  "artifact",
  "axe-common",
  "axe-double-common",
  "axe-double-rare",
  "axe-double-uncommon",
  "axe-rare",
  "axe-uncommon",
  "barrel",
  "barrel-dark",
  "bench",
  "book-a",
  "book-b",
  "book-c",
  "book-d",
  "book-e",
  "book-f",
  "book-open-a",
  "book-open-b",
  "bookcase",
  "bookcase-filled",
  "bookcase-wide",
  "bookcase-wide-broken",
  "bookcase-wide-filled",
  "bookcase-wide-filled-broken",
  "bricks",
  "bucket",
  "chair-rounded",
  "chest-common",
  "chest-common-empty",
  "chest-rare",
  "chest-rare-mimic-closed",
  "chest-top-common",
  "chest-top-rare",
  "chest-top-uncommon",
  "chest-uncommon",
  "chest-uncommon-closed",
  "coin-crown",
  "coins-large",
  "coins-medium",
  "coins-small",
  "crate-dark",
  "crate-platform-large",
  "crossbow-common",
  "crossbow-rare",
  "crossbow-uncommon",
  "dagger-common",
  "dagger-rare",
  "dagger-uncommon",
  "door",
  "door-gate",
  "floor-decoration-shattered-bricks",
  "floor-decoration-tiles-large",
  "floor-decoration-tiles-small",
  "floor-decoration-wood",
  "floor-decoration-wood-left",
  "floor-decoration-wood-right",
  "hammer-common",
  "hammer-rare",
  "hammer-uncommon",
  "loot-sack-a",
  "loot-sack-b",
  "mug",
  "pillar-broken",
  "plate-full",
  "plate-half",
  "plate-rounded",
  "pot-a",
  "pot-a-decorated",
  "pot-b",
  "pot-b-decorated",
  "pot-c",
  "pot-c-decorated",
  "potion-large-green",
  "potion-large-red",
  "potion-medium-green",
  "potion-medium-red",
  "potion-small-green",
  "potion-small-red",
  "pots",
  "quiver-empty",
  "quiver-full",
  "quiver-half-full",
  "scaffold-high",
  "scaffold-high-corner-both",
  "scaffold-high-corner-left",
  "scaffold-high-corner-right",
  "scaffold-high-railing",
  "scaffold-low",
  "scaffold-low-corner-both",
  "scaffold-low-corner-left",
  "scaffold-low-corner-right",
  "scaffold-low-railing",
  "scaffold-medium",
  "scaffold-medium-corner-both",
  "scaffold-medium-corner-left",
  "scaffold-medium-corner-right",
  "scaffold-medium-railing",
  "scaffold-small-high",
  "scaffold-small-high-corner-left",
  "scaffold-small-high-corner-right",
  "scaffold-small-high-long",
  "scaffold-small-high-railing",
  "scaffold-small-high-railing-long",
  "scaffold-small-low",
  "scaffold-small-low-corner-left",
  "scaffold-small-low-corner-right",
  "scaffold-small-low-long",
  "scaffold-small-low-railing",
  "scaffold-small-low-railing-long",
  "scaffold-small-medium",
  "scaffold-small-medium-corner-left",
  "scaffold-small-medium-corner-right",
  "scaffold-small-medium-long",
  "scaffold-small-medium-railing",
  "scaffold-small-medium-railing-long",
  "scaffold-stairs",
  "shield-common",
  "shield-rare",
  "shield-uncommon",
  "spell-book",
  "staff-common",
  "staff-rare",
  "staff-uncommon",
  "stool-rounded",
  "sword-common",
  "sword-rare",
  "sword-uncommon",
  "table-large",
  "table-medium-rounded",
  "table-small-rounded",
  "tile-brick-a-large",
  "tile-brick-b-large",
  "torch",
  "torch-wall",
  "trapdoor",
  "weapon-rack"
 ]
},
 {
 "slug": "kay-dun-2",
 "name": "kay-dun-2",
 "url": "https://www.kaylousberg.com",
 "models": [
   "barrel-large",
   "barrel-large-decorated",
   "barrel-small",
   "barrel-small-stack",
   "bed-decorated",
   "bed-floor",
   "bed-frame",
   "bottle-a-brown",
   "bottle-a-green",
   "bottle-a-labeled-brown",
   "bottle-a-labeled-green",
   "bottle-b-brown",
   "bottle-b-green",
   "bottle-c-brown",
   "bottle-c-green",
   "box-small-decorated",
   "box-stacked",
   "candle",
   "candle-lit",
   "candle-melted",
   "candle-thin",
   "candle-thin-lit",
   "candle-triple",
   "ceiling-tile",
   "chair",
   "chest",
   "chest-gold",
   "coin",
   "coin-stack-large",
   "coin-stack-medium",
   "coin-stack-small",
   "column",
   "crates-stacked",
   "floor-dirt-large",
   "floor-dirt-large-rocky",
   "floor-dirt-small-a",
   "floor-dirt-small-b",
   "floor-dirt-small-c",
   "floor-dirt-small-corner",
   "floor-dirt-small-d",
   "floor-dirt-small-weeds",
   "floor-foundation-allsides",
   "floor-foundation-corner",
   "floor-foundation-diagonal-corner",
   "floor-foundation-front",
   "floor-foundation-front-and-back",
   "floor-foundation-front-and-sides",
   "floor-tile-big-grate-open",
   "floor-tile-big-spikes",
   "floor-tile-extralarge-grates-open",
   "floor-tile-grate-open",
   "floor-tile-large",
   "floor-tile-large-rocks",
   "floor-tile-small",
   "floor-tile-small-broken-a",
   "floor-tile-small-broken-b",
   "floor-tile-small-corner",
   "floor-tile-small-decorated",
   "floor-tile-small-weeds-a",
   "floor-tile-small-weeds-b",
   "floor-wood-large",
   "floor-wood-large-dark",
   "floor-wood-small",
   "floor-wood-small-dark",
   "keg",
   "keg-decorated",
   "key",
   "keyring",
   "keyring-hanging",
   "pillar",
   "plate",
   "plate-food-a",
   "plate-food-b",
   "plate-small",
   "plate-stack",
   "rubble-half",
   "rubble-large",
   "shelf-large",
   "shelf-small",
   "shelf-small-candles",
   "shelves",
   "stairs",
   "stairs-long",
   "stairs-narrow",
   "stairs-wall-left",
   "stairs-wall-right",
   "stairs-walled",
   "stairs-wide",
   "stairs-wood",
   "stairs-wood-decorated",
   "stool",
   "sword-shield",
   "sword-shield-gold",
   "table-long",
   "table-long-broken",
   "table-long-decorated-a",
   "table-long-decorated-c",
   "table-medium",
   "table-medium-broken",
   "table-medium-decorated-a",
   "table-small",
   "table-small-decorated-a",
   "table-small-decorated-b",
   "torch",
   "torch-lit",
   "torch-mounted",
   "trunk-large-c",
   "trunk-medium-c",
   "trunk-small-c",
   "wall",
   "wall-arched",
   "wall-archedwindow-gated",
   "wall-archedwindow-gated-scaffold",
   "wall-archedwindow-open",
   "wall-broken",
   "wall-corner",
   "wall-corner-gated",
   "wall-corner-scaffold",
   "wall-corner-small",
   "wall-cracked",
   "wall-crossing",
   "wall-doorway",
   "wall-doorway-scaffold",
   "wall-doorway-sides",
   "wall-doorway-tsplit",
   "wall-endcap",
   "wall-gated",
   "wall-half",
   "wall-half-endcap",
   "wall-half-endcap-sloped",
   "wall-open-scaffold",
   "wall-pillar",
   "wall-scaffold",
   "wall-shelves",
   "wall-sloped",
   "wall-tsplit",
   "wall-tsplit-sloped",
   "wall-window-closed",
   "wall-window-closed-scaffold",
   "wall-window-open",
   "wall-window-open-scaffold"
  ]
},
 {
  "slug": "fs-terrain",
  "name": "fs-terrain",
  "url": null,
  "outsideCatalog": [
   "cave-prop-entrance", "cave-prop-minecart", "cave-prop-pick-large", "cave-prop-pick-small",
   "cave-prop-railway-bumpstop", "cave-prop-railway-curve-large",
   "cave-prop-railway-curve-small", "cave-prop-railway-hill-gentle",
   "cave-prop-railway-hill-sharp", "cave-prop-railway-intersection",
   "cave-prop-railway-straight-a", "cave-prop-railway-straight-b",
   "cave-prop-railway-straight-c", "cave-prop-railway-straight-d", "cave-prop-railway-switch",
   "cave-prop-stalagmite-connected-base", "cave-prop-stalagmite-connected-mid",
   "cave-prop-stalagmite-connected-top", "cave-prop-stalagmite-normal",
   "cave-prop-stalagmite-tiny", "cave-prop-support-ceiling-beam-a",
   "cave-prop-support-ceiling-beam-b", "cave-prop-support-ceiling-beam-c",
   "cave-prop-support-ceiling-beam-d", "cave-prop-support-ceiling-boards-a",
   "cave-prop-support-ceiling-boards-b", "cave-prop-support-ceiling-boards-c",
   "cave-prop-support-ceiling-boards-d", "cave-prop-support-corner-brace-a",
   "cave-prop-support-corner-brace-b", "cave-prop-support-wall-boards-a",
   "cave-prop-support-wall-boards-b", "cave-prop-support-wall-boards-c",
   "cave-prop-support-wall-boards-d", "cave-prop-support-wall-pillar-a",
   "cave-prop-support-wall-pillar-b", "cave-prop-support-wall-pillar-c",
   "cave-prop-support-wall-pillar-d"
  ],
  "models": [
   "beach-prop-coconut",
   "beach-prop-docks-corner",
   "beach-prop-docks-corner-supports",
   "beach-prop-docks-steps",
   "beach-prop-docks-straight",
   "beach-prop-docks-straight-supports",
   "beach-prop-shell-a",
   "beach-prop-shell-b",
   "beach-prop-starfish-a",
   "beach-prop-starfish-b",
   "beach-prop-tree-palm-a",
   "beach-prop-tree-palm-b",
   "beach-prop-tree-palm-c",
   "cave-prop-entrance",
   "cave-prop-minecart",
   "cave-prop-pick-large",
   "cave-prop-pick-small",
   "cave-prop-railway-bumpstop",
   "cave-prop-railway-curve-large",
   "cave-prop-railway-curve-small",
   "cave-prop-railway-hill-gentle",
   "cave-prop-railway-hill-sharp",
   "cave-prop-railway-intersection",
   "cave-prop-railway-straight-a",
   "cave-prop-railway-straight-b",
   "cave-prop-railway-straight-c",
   "cave-prop-railway-straight-d",
   "cave-prop-railway-switch",
   "cave-prop-stalagmite-connected-base",
   "cave-prop-stalagmite-connected-mid",
   "cave-prop-stalagmite-connected-top",
   "cave-prop-stalagmite-normal",
   "cave-prop-stalagmite-tiny",
   "cave-prop-support-ceiling-beam-a",
   "cave-prop-support-ceiling-beam-b",
   "cave-prop-support-ceiling-beam-c",
   "cave-prop-support-ceiling-beam-d",
   "cave-prop-support-ceiling-boards-a",
   "cave-prop-support-ceiling-boards-b",
   "cave-prop-support-ceiling-boards-c",
   "cave-prop-support-ceiling-boards-d",
   "cave-prop-support-corner-brace-a",
   "cave-prop-support-corner-brace-b",
   "cave-prop-support-wall-boards-a",
   "cave-prop-support-wall-boards-b",
   "cave-prop-support-wall-boards-c",
   "cave-prop-support-wall-boards-d",
   "cave-prop-support-wall-pillar-a",
   "cave-prop-support-wall-pillar-b",
   "cave-prop-support-wall-pillar-c",
   "cave-prop-support-wall-pillar-d",
   "hilly-prop-branch-a",
   "hilly-prop-branch-b",
   "hilly-prop-branch-c",
   "hilly-prop-camp-campfire",
   "hilly-prop-camp-wood-pile",
   "hilly-prop-cattail-a",
   "hilly-prop-cattail-b",
   "hilly-prop-fence-boards-a",
   "hilly-prop-fence-boards-b",
   "hilly-prop-fence-boards-c",
   "hilly-prop-fence-boards-d",
   "hilly-prop-fence-curve-1x1",
   "hilly-prop-fence-curve-2x2",
   "hilly-prop-fence-curve-3x3",
   "hilly-prop-fence-gate-a",
   "hilly-prop-fence-gate-b",
   "hilly-prop-fence-post-a",
   "hilly-prop-fence-post-b",
   "hilly-prop-fence-post-c",
   "hilly-prop-fence-post-d",
   "hilly-prop-flower-daisy",
   "hilly-prop-flower-lily-blue",
   "hilly-prop-flower-lily-pink",
   "hilly-prop-flower-rose",
   "hilly-prop-flower-sunflower",
   "hilly-prop-flower-tulip",
   "hilly-prop-grass-clump-a",
   "hilly-prop-grass-clump-b",
   "hilly-prop-grass-clump-c",
   "hilly-prop-grass-clump-d",
   "hilly-prop-mushroom-a",
   "hilly-prop-mushroom-b",
   "hilly-prop-rock-a",
   "hilly-prop-rock-b",
   "hilly-prop-rock-c",
   "hilly-prop-rock-d",
   "hilly-prop-ruins-pillar-a",
   "hilly-prop-ruins-pillar-b",
   "hilly-prop-ruins-pillar-c",
   "hilly-prop-ruins-pillar-d",
   "hilly-prop-ruins-pillar-e",
   "hilly-prop-stepping-stones-a",
   "hilly-prop-stepping-stones-b",
   "hilly-prop-stepping-stones-c",
   "hilly-prop-stepping-stones-d",
   "hilly-prop-stepping-stones-e",
   "hilly-prop-stepping-stones-f",
   "hilly-prop-stepping-stones-g",
   "hilly-prop-stepping-stones-h",
   "hilly-prop-stump",
   "hilly-prop-tree-cedar-a",
   "hilly-prop-tree-cedar-b",
   "hilly-prop-tree-oak-a",
   "hilly-prop-tree-oak-b",
   "hilly-prop-tree-oak-c",
   "hilly-prop-tree-oak-d",
   "hilly-prop-tree-pine-a",
   "hilly-prop-tree-pine-b",
   "hilly-prop-tree-pine-c",
   "mountain-a",
   "mountain-b",
   "mountain-c",
   "mountain-d",
   "shared-prop-boulder-a",
   "shared-prop-boulder-b",
   "shared-prop-boulder-c",
   "shared-prop-boulder-d",
   "shared-prop-boulder-e",
   "shared-prop-boulder-f"
  ]
 },
 {
  "slug": "ken-proto",
  "name": "ken-proto",
  "url": "https://kenney.nl/assets/prototype-kit",
  "models": [
   "coin",
   "lever-double",
   "lever-single"
  ]
 },
 {
  "slug": "kay-hallow",
  "name": "kay-hallow",
  "url": "https://www.kaylousberg.com",
  "models": [
   "bench",
   "bone-a",
   "bone-b",
   "bone-c",
   "candle",
   "candle-melted",
   "candle-thin",
   "candle-triple",
   "coffin-lid",
   "floor-dirt",
   "floor-dirt-grave",
   "floor-dirt-small",
   "lantern-hanging",
   "lantern-standing",
   "path-a",
   "path-b",
   "path-c",
   "path-d",
   "post",
   "post-lantern",
   "ribcage",
   "skull",
   "tree-dead-large",
   "tree-dead-medium",
   "tree-dead-small",
   "tree-pine-orange-large",
   "tree-pine-orange-medium",
   "tree-pine-orange-small",
   "tree-pine-yellow-large",
   "tree-pine-yellow-medium",
   "tree-pine-yellow-small"
  ]
 },
 {
  "slug": "kay-food",
  "name": "kay-food",
  "url": "https://www.kaylousberg.com",
  "models": [
   "bowl",
   "bowl-dirty",
   "bowl-small",
   "chair-b",
   "crate",
   "crate-ham",
   "crate-lid",
   "crate-potatoes",
   "crate-steak",
   "cutting-board",
   "door-b",
   "food-dinner",
   "food-ingredient-carrot",
   "food-ingredient-carrot-chopped",
   "food-ingredient-carrot-pieces",
   "food-ingredient-cheese",
   "food-ingredient-cheese-chopped",
   "food-ingredient-ham",
   "food-ingredient-ham-cooked",
   "food-ingredient-lettuce",
   "food-ingredient-lettuce-chopped",
   "food-ingredient-onion",
   "food-ingredient-onion-chopped",
   "food-ingredient-onion-rings",
   "food-ingredient-potato",
   "food-ingredient-potato-chopped",
   "food-ingredient-steak",
   "food-ingredient-tomato",
   "food-ingredient-tomato-slice",
   "food-ingredient-tomato-slices",
   "food-stew",
   "jar-c-large",
   "jar-c-medium",
   "jar-c-small",
   "knife",
   "pan-006",
   "pan-a",
   "pan-b",
   "plate",
   "plate-small",
   "pot-a",
   "pot-b",
   "pot-large",
   "table-round-b"
  ]
 },
 {
  "slug": "quat-props",
  "name": "quat-props",
  "url": "https://quaternius.com/",
  "models": [
   "bag",
   "barrel-apples",
   "book-5",
   "book-7",
   "book-group-medium-1",
   "book-group-medium-2",
   "book-group-medium-3",
   "book-group-small-1",
   "book-group-small-2",
   "book-group-small-3",
   "book-simplified-single",
   "book-stack-1",
   "book-stack-2",
   "bottle-1",
   "bucket-wooden-1",
   "cage-small",
   "chalice",
   "key-gold",
   "key-metal",
   "mug",
   "potion-2",
   "potion-4",
   "pouch-large",
   "scroll-1",
   "scroll-2",
   "shield-wooden",
   "table-plate",
   "torch-metal",
   "training-dummy",
   "vase-2",
   "vase-4",
   "weapon-stand"
  ]
 },
 {
  "slug": "quat-nature",
  "name": "quat-nature",
  "url": "https://quaternius.com/",
  "models": [
   "cactus-2",
   "cactus-3",
   "cactus-4",
   "cactus-5",
   "cactus-flower-1",
   "cactus-flower-2",
   "cactus-flower-3",
   "cactus-flower-4",
   "log",
   "plant-1",
   "rock-1",
   "rock-2",
   "rock-3",
   "rock-4",
   "rock-5",
   "rock-6",
   "rock-7",
   "tree-birch-dead-1",
   "tree-birch-dead-2",
   "tree-birch-dead-3",
   "tree-birch-dead-4",
   "tree-birch-dead-5",
   "tree-common-dead-1",
   "tree-common-dead-2",
   "tree-common-dead-3",
   "tree-common-dead-4",
   "tree-common-dead-5",
   "tree-pine-1",
   "tree-pine-3",
   "tree-willow-dead-1",
   "tree-willow-dead-2",
   "tree-willow-dead-3",
   "tree-willow-dead-4",
   "tree-willow-dead-5",
   "wheat"
  ]
 },
 {
  "slug": "natuur",
  "name": "natuur",
  "url": null,
  "models": [
   "branch-1",
   "branch-2",
   "branch-3",
   "campfire-star",
   "campfire-teepee",
   "cattail-1",
   "cattail-2",
   "cattail-3",
   "cattail-4",
   "cattail-5",
   "coconut",
   "flower-balloon-1",
   "flower-balloon-2",
   "flower-balloon-3",
   "flower-bellflower-1",
   "flower-bellflower-2",
   "flower-bellflower-3",
   "flower-daisy-1",
   "flower-daisy-2",
   "flower-daisy-3",
   "flower-sunflower-1",
   "flower-sunflower-2",
   "flower-sunflower-3",
   "flower-violet-1",
   "flower-violet-2",
   "flower-violet-3",
   "grass-clump-1",
   "grass-clump-2",
   "grass-clump-3",
   "grass-clump-4",
   "grass-clump-5",
   "lamp-post",
   "log-1",
   "log-2",
   "log-3",
   "log-4",
   "log-5",
   "mountain-2",
   "mountain-3",
   "mountain-4",
   "mushroom-brown",
   "mushroom-dark-red",
   "mushroom-grey",
   "mushroom-red-spotted",
   "rock-1",
   "rock-2",
   "rock-3",
   "rock-4",
   "rock-5",
   "rock-6",
   "rock-7",
   "rock-8",
   "rock-9",
   "root-1",
   "root-2",
   "root-3",
   "root-4",
   "root-5",
   "root-6",
   "shell-layered",
   "shell-salmon",
   "shell-slate",
   "starfish-bleached",
   "starfish-salmon",
   "stepping-stone-1",
   "stepping-stone-2",
   "stepping-stone-3",
   "stepping-stone-4",
   "stump-1",
   "stump-2",
   "stump-3",
   "timber-cut-1",
   "timber-cut-2",
   "timber-cut-3",
   "timber-cut-4",
   "timber-stack-1",
   "timber-stack-2",
   "timber-whole-1",
   "tree-bare-1",
   "tree-bare-2",
   "tree-bare-3",
   "tree-bare-4",
   "tree-bare-5",
   "tree-bare-6",
   "tree-palm-1",
   "tree-palm-2",
   "tree-palm-3",
   "tree-palm-4",
   "tree-palm-5",
   "tree-palm-6",
   "tree-pine-1",
   "tree-pine-2",
   "tree-pine-3"
  ]
 },
 {
  "slug": "quat-pirate",
  "name": "quat-pirate",
  "url": "https://quaternius.com/packs/piratekit.html",
  "models": [
   "anchor",
   "axe",
   "axe-double",
   "axe-rifle",
   "barrel",
   "bomb",
   "bones-large",
   "bottle-1",
   "bottle-2",
   "bucket",
   "bucket-fishes",
   "cannon",
   "cannonball",
   "chest",
   "chest-gold",
   "chicken-leg",
   "cliff-1",
   "cliff-2",
   "cliff-3",
   "cliff-4",
   "coins",
   "cutlass",
   "dagger",
   "dock-pole",
   "fish-mackerel",
   "fish-tuna",
   "gold-bag",
   "house-1",
   "house-2",
   "house-3",
   "logs",
   "lute",
   "papers",
   "pirate-anne",
   "pirate-captain",
   "pirate-henry",
   "pirate-mako",
   "pirate-sharky",
   "pistol",
   "red-x",
   "rifle",
   "rock-1",
   "rock-2",
   "rock-3",
   "rock-4",
   "rock-5",
   "sawmill",
   "shark",
   "ship-large",
   "ship-small",
   "shotgun-double",
   "skeleton",
   "skeleton-headless",
   "skull",
   "skulls",
   "sword-1",
   "sword-2",
   "swords",
   "tentacle",
   "tree-palm-1",
   "tree-palm-2",
   "tree-palm-3",
   "wheat"
  ]
 },
 {
 "slug": "quat-dun-1",
 "name": "quat-dun-1",
 "url": "https://quaternius.com/packs/modulardungeon.html",
 "models": [
   "arch-door-bottompivot",
   "bag-coins",
   "bag-standing",
   "barrel-2",
   "chest",
   "chest-gold",
   "coins",
   "crate",
   "pedestal",
   "pedestal-2",
   "sword-wall-mount",
   "trapdoor",
   "trapdoor-open",
   "vase"
  ]
},
 {
 "slug": "quat-dun-2",
 "name": "quat-dun-2",
 "url": "https://quaternius.com/packs/modulardungeon.html",
 "models": [
   "arch",
   "arch-door",
   "arch-door-bottompivot",
   "bag-coins",
   "bag-standing",
   "barrel-2",
   "bucket",
   "chest",
   "chest-gold",
   "cobweb",
   "cobweb-2",
   "coins",
   "column",
   "crate",
   "floor-bricks-separate",
   "floor-modular",
   "pedestal",
   "pedestal-2",
   "skull",
   "stairs-modular",
   "stairs-side-cover",
   "stairs-side-cover-wall",
   "statue-horse",
   "sword-wall-mount",
   "trapdoor",
   "trapdoor-open",
   "vase",
   "wall-cover-modular",
   "wall-modular"
  ]
},
 {
  "slug": "quat-rpg",
  "name": "quat-rpg",
  "url": "https://quaternius.com/packs/ultimaterpg.html",
  "models": [
   "armor-horned",
   "armor-horned-golden",
   "armor-leather",
   "armor-metal",
   "armor-metal-2",
   "arrow",
   "arrow-golden",
   "axe-double",
   "axe-small",
   "backpack",
   "bag",
   "bone",
   "book-1-closed",
   "book-1-open",
   "book-2-closed",
   "book-2-open",
   "book-3-closed",
   "book-3-open",
   "book-4-closed",
   "book-4-open",
   "bow-golden",
   "bow-wooden",
   "chalice",
   "chest-closed",
   "chest-ingots",
   "chest-open",
   "coin",
   "coin-skull",
   "coin-star",
   "crown",
   "crown-2",
   "dagger",
   "dart",
   "fish-bone",
   "glove",
   "gold-ingots",
   "hammer-double",
   "heart",
   "key-1",
   "key-2",
   "key-3",
   "key-4",
   "necklace-1",
   "necklace-2",
   "necklace-3",
   "padlock",
   "parchment",
   "potion-1-empty",
   "potion-1-filled",
   "potion-10-empty",
   "potion-10-filled",
   "potion-11-empty",
   "potion-11-filled",
   "potion-2-empty",
   "potion-2-filled",
   "potion-3-empty",
   "potion-3-filled",
   "potion-4-empty",
   "potion-4-filled",
   "potion-5-empty",
   "potion-5-filled",
   "potion-6-empty",
   "potion-6-filled",
   "potion-7-empty",
   "potion-7-filled",
   "potion-8-empty",
   "potion-8-filled",
   "potion-9-empty",
   "potion-9-filled",
   "pouch",
   "ring-1",
   "ring-2",
   "ring-3",
   "ring-4",
   "ring-5",
   "ring-6",
   "ring-7",
   "scroll",
   "skull",
   "skull-2",
   "star",
   "sword",
   "sword-big"
  ]
 },
 {
  "slug": "quat-food",
  "name": "quat-food",
  "url": "https://quaternius.com/packs/ultimatefood.html",
  "models": [
   "apple",
   "avocado",
   "bacon-cooked",
   "banana",
   "bottle-1",
   "bottle-2",
   "bread",
   "bread-slice",
   "broccoli",
   "chicken-leg",
   "chocolate-bar",
   "chopsticks",
   "coconut",
   "coconut-half",
   "cooking-pot",
   "cooking-pot-2",
   "cooking-pot-2-soup",
   "cooking-pot-soup",
   "croissant",
   "cupcake",
   "donut-1",
   "donut-2",
   "donut-3",
   "donut-4",
   "egg-whole-white",
   "eggplant",
   "fish",
   "fish-bone",
   "fork",
   "frying-pan",
   "hotdog",
   "ice-cream-1",
   "ice-cream-2",
   "ice-cream-3",
   "ice-cream-4",
   "knife",
   "lettuce-whole",
   "mushroom",
   "mushroom-sliced",
   "peanut-butter",
   "pepper-green",
   "pepper-red",
   "plate",
   "plate-2",
   "popsicle-chocolate",
   "popsicle-multiple",
   "pumpkin",
   "sashimi-salmon",
   "soy-sauce",
   "spoon",
   "steak",
   "sushi-nigiri-1",
   "sushi-roll-1",
   "sushi-roll-2",
   "tentacle",
   "tomato-slice",
   "waffle"
  ]
 },
 {
  "slug": "quat-fish",
  "name": "quat-fish",
  "url": "https://quaternius.com/packs/animatedfish.html",
  "models": [
   "dolphin",
   "fish-1",
   "fish-2",
   "fish-3",
   "manta-ray",
   "shark",
   "whale"
  ]
 },
 {
  "slug": "quat-ships",
  "name": "quat-ships",
  "url": "https://quaternius.com/packs/ships.html",
  "models": [
   "boat",
   "boat-sail",
   "ship-sail",
   "viking-boat"
  ]
 },
 {
  "slug": "ken-castle",
  "name": "ken-castle",
  "url": "https://kenney.nl/assets/castle-kit",
  "models": [
   "bridge-straight",
   "bridge-straight-pillar",
   "gate",
   "metal-gate",
   "tower-square-mid-open",
   "tower-square-mid-open-simple",
   "tree-large",
   "tree-small"
  ]
 },
 {
  "slug": "ken-grave",
  "name": "ken-grave",
  "url": "https://kenney.nl/assets/graveyard-kit",
  "models": [
   "altar-stone",
   "altar-wood",
   "coffin-old",
   "crypt-large",
   "crypt-large-roof",
   "detail-bowl",
   "detail-chalice",
   "detail-plate",
   "grave",
   "grave-border",
   "iron-fence",
   "iron-fence-bar",
   "iron-fence-border",
   "iron-fence-border-column",
   "iron-fence-border-curve",
   "iron-fence-border-gate",
   "iron-fence-curve",
   "iron-fence-damaged",
   "lightpost-single",
   "pumpkin-tall-carved",
   "shovel",
   "stone-wall",
   "stone-wall-column",
   "stone-wall-curve",
   "stone-wall-damaged"
  ]
 },
 {
  "slug": "kay-adventurers",
  "name": "kay-adventurers",
  "url": "https://www.kaylousberg.com",
  "outsideCatalog": [
   "shield-round-colored"
  ],
  "models": [
   "arrow-bow",
   "arrow-bow-bundle",
   "arrow-crossbow",
   "arrow-crossbow-bundle",
   "axe-one-handed",
   "axe-two-handed",
   "barbarian",
   "bow",
   "bow-strung",
   "crossbow-one-handed",
   "crossbow-two-handed",
   "dagger",
   "knight",
   "mage",
   "mug-empty",
   "mug-full",
   "quiver",
   "ranger",
   "rogue",
   "rogue-hooded",
   "shield-badge",
   "shield-badge-colored",
   "shield-round",
   "shield-round-barbarian",
   "shield-round-colored",
   "shield-spikes",
   "shield-spikes-colored",
   "shield-square",
   "shield-square-colored",
   "smokebomb",
   "spellbook-closed",
   "spellbook-open",
   "staff",
   "sword-one-handed",
   "sword-two-handed",
   "sword-two-handed-colored",
   "wand"
  ]
 },
 {
  "slug": "kay-skeleton",
  "name": "kay-skeleton",
  "url": "https://www.kaylousberg.com",
  "models": [
   "arrow",
   "arrow-broken",
   "arrow-broken-half",
   "arrow-half",
   "axe",
   "blade",
   "crossbow",
   "quiver",
   "shield-large-a",
   "shield-large-b",
   "shield-small-a",
   "shield-small-b",
   "skeleton-mage",
   "skeleton-minion",
   "skeleton-rogue",
   "skeleton-warrior",
   "staff"
  ]
 },
 {
  "slug": "small-props",
  "name": "small-props",
  "url": null,
  "models": [
   "anvil-b",
   "bag-1-c",
   "bag-2-c",
   "bag-3-c",
   "basin-a",
   "boat-frame-a",
   "broom-a",
   "bucket-1-a",
   "cart-1-a",
   "cut-wood-1-a",
   "dried-fish-1-a",
   "fireplace-1-1-a",
   "fishing-rod-a",
   "fishing-rod-b",
   "fishing-rod-c",
   "hammer-1-a",
   "laundry-a",
   "mannequin-1-a",
   "mannequin-2-a",
   "nail-a",
   "pitchfork-a",
   "practice-target-1-a",
   "practice-target-2-a",
   "skin-hang-a",
   "stool-a",
   "trough-1-a",
   "trough-3-a",
   "wheel-a"
  ]
 },
 {
  "slug": "kay-weapons",
  "name": "kay-weapons",
  "url": "https://www.kaylousberg.com",
  "models": [
   "arrow-a",
   "arrow-b",
   "axe-a",
   "axe-b",
   "axe-c",
   "bow-a",
   "bow-a-with-string",
   "bow-b",
   "bow-b-with-string",
   "dagger-a",
   "dagger-b",
   "fistweapon-a",
   "fistweapon-a-stacked",
   "fistweapon-b",
   "fistweapon-b-stacked",
   "halberd",
   "hammer-a",
   "hammer-b",
   "hammer-c",
   "shield-a",
   "shield-b",
   "shield-c",
   "spear-a",
   "staff-a",
   "staff-b",
   "sword-a",
   "sword-b",
   "sword-c",
   "sword-d",
   "sword-e",
   "wand-a"
  ]
 },
 {
  "slug": "isa-food",
  "name": "isa-food",
  "url": "https://www.isalousberg.com",
  "models": [
   "baguette",
   "baguette-half",
   "baguette-slice",
   "bread",
   "bread-half",
   "bread-roll",
   "bread-slice",
   "cake-birthday",
   "cake-birthday-cut",
   "cake-birthday-slice",
   "cake-chocolate",
   "cake-chocolate-cut",
   "cake-chocolate-slice",
   "cake-strawberry",
   "cake-strawberry-cut",
   "cake-strawberry-slice",
   "cinnamon-roll",
   "cookie",
   "croissant",
   "cupcake",
   "donut",
   "donut-chocolate",
   "donut-pink",
   "muffin",
   "pie-apple",
   "pie-apple-cut",
   "pie-apple-slice",
   "pie-cherry",
   "pie-cherry-cut",
   "pie-cherry-slice",
   "waffle",
   "waffle-stacked"
  ]
 },
 {
  "slug": "clay-props",
  "name": "clay-props",
  "url": "https://glitchpixelinteractive.com/",
  "models": [
   "bowl",
   "crockpot",
   "crockpot-lid",
   "cup",
   "jug",
   "planter",
   "plate",
   "platter",
   "rice-pot",
   "wide-vase"
  ]
 },
 {
  "slug": "kay-furniture",
  "name": "kay-furniture",
  "url": "https://www.kaylousberg.com",
  "models": [
   "armchair",
   "bed-single-a",
   "bed-single-b",
   "cabinet-medium",
   "cabinet-small",
   "chair-a-wood",
   "chair-b-wood",
   "chair-stool-wood",
   "couch-pillows",
   "rug-oval-a",
   "rug-rectangle-stripes-a",
   "shelf-a-big",
   "shelf-b-small",
   "table-low",
   "table-medium",
   "table-medium-long",
   "table-small"
  ]
 },
 {
 "slug": "ken-mini-dun",
 "name": "ken-mini-dun",
 "url": "https://kenney.nl/assets/mini-dungeon",
 "models": [
   "banner",
   "barrel",
   "chair",
   "chest",
   "coin",
   "shield-rectangle",
   "shield-round",
   "table",
   "wood-structure",
   "wood-support"
  ]
},
 {
  "slug": "tropical-island",
  "name": "tropical-island",
  "models": [
   "barrel",
   "sword-pirate",
   "tent"
  ]
 },
 {
  "slug": "windmill",
  "name": "windmill",
  "models": [
   "windmill"
  ]
 },
 {
  "slug": "primitive-tools",
  "name": "primitive-tools",
  "url": null,
  "models": [
   "bow",
   "stone-arrow",
   "stone-axe",
   "stone-club",
   "stone-hammer",
   "stone-knife",
   "stone-pickaxe",
   "stone-shield",
   "stone-shovel",
   "stone-spear",
   "torch",
   "wooden-arrow",
   "wooden-axe",
   "wooden-club",
   "wooden-hammer",
   "wooden-knife",
   "wooden-pickaxe",
   "wooden-shield",
   "wooden-shovel",
   "wooden-spear"
  ]
 },
 {
  "slug": "isa-pond",
  "name": "isa-pond",
  "url": null,
  "models": [
   "bird",
   "branch",
   "branch-b",
   "brown-bird",
   "clay-pot",
   "dragonfly",
   "green-frog",
   "metal-tub",
   "red-dragonfly",
   "rock-a",
   "rock-a-2",
   "rock-a-3",
   "round-bird",
   "tree-branch",
   "tree-branch-2",
   "tree-branch-3",
   "tree-branch-4",
   "wooden-tub",
   "yellow-frog"
  ]
 },
 {
  "slug": "isa-park",
  "name": "isa-park",
  "url": null,
  "models": [
   "bench",
   "flower-a",
   "flower-b",
   "fountain",
   "grass-a",
   "grass-b",
   "street-lantern",
   "tree",
   "tree-large"
  ]
 },
 {
  "slug": "medieval-town",
  "name": "medieval-town",
  "url": null,
  "models": [
   "bag",
   "bag-open",
   "bags",
   "barrel",
   "bell",
   "bell-tower",
   "bench",
   "bench-2",
   "blacksmith",
   "bonfire",
   "cart",
   "cauldron",
   "crate",
   "door-round",
   "door-straight",
   "fantasy-barracks",
   "fantasy-house",
   "fantasy-house-2",
   "fantasy-house-3",
   "fantasy-inn",
   "fantasy-sawmill",
   "fantasy-stable",
   "fence",
   "gazebo",
   "hay",
   "market-stand",
   "market-stand-2",
   "mill",
   "package",
   "package-2",
   "sawmill-saw",
   "smoke",
   "well"
  ]
 },
 {
  "slug": "isa-plants",
  "name": "isa-plants",
  "url": "https://www.isalousberg.com",
  "models": [
   "cactus-a",
   "cactus-b",
   "cactus-c",
   "cactus-d",
   "monstera-plant-large",
   "monstera-plant-medium",
   "monstera-plant-small",
   "pot-a-large",
   "pot-a-medium",
   "pot-a-small",
   "pothos-plant-large",
   "pothos-plant-medium",
   "pothos-plant-small",
   "pots-stacked",
   "sansevieria-plant-large",
   "sansevieria-plant-medium",
   "sansevieria-plant-small",
   "saucer-a-large",
   "saucer-a-medium",
   "saucer-a-small",
   "shovel",
   "succulent-a",
   "succulent-b",
   "succulent-c",
   "succulent-d",
   "watering-can-a",
   "watering-can-b",
   "yucca-branch-medium-a",
   "yucca-branch-medium-b",
   "yucca-branch-medium-c",
   "yucca-plant-large",
   "yucca-plant-medium",
   "yucca-plant-small",
   "zzplant-plant-large",
   "zzplant-plant-medium",
   "zzplant-plant-small"
  ]
 },
 {
  "slug": "ken-holiday",
  "name": "ken-holiday",
  "url": "https://kenney.nl/assets/holiday-kit",
  "models": [
   "cabin-fence",
   "cabin-roof-dormer",
   "gingerbread-man",
   "gingerbread-woman",
   "hanukkah-menorah",
   "hanukkah-menorah-candles",
   "lights-colored",
   "sled",
   "sled-long",
   "snowman",
   "snowman-hat",
   "tree"
  ]
 },
 {
  "slug": "desert-buildings",
  "name": "desert-buildings",
  "url": null,
  "models": [
   "awning-a",
   "awning-b",
   "barrel",
   "crate",
   "door",
   "ladder-a",
   "ladder-b",
   "large-building-a",
   "large-building-b",
   "large-building-c",
   "large-building-d",
   "large-building-frame-a",
   "large-building-frame-b",
   "large-building-frame-c",
   "large-building-frame-d",
   "medium-building-a",
   "medium-building-b",
   "medium-building-frame-a",
   "medium-building-frame-b",
   "small-building-a",
   "small-building-frame-a",
   "well"
  ]
 },
 {
  "slug": "jelly-forest",
  "name": "jelly-forest",
  "url": null,
  "licenseLabel": "JellySquish asset licence",
  "models": [
   "log",
   "mushrooms-1",
   "tent",
   "tree-3"
  ]
 },
 {
  "slug": "medieval-forge",
  "name": "medieval-forge",
  "url": null,
  "models": [
   "anvil",
   "armor-stand",
   "barrel",
   "barrel-2",
   "box",
   "box-2",
   "bridge",
   "bridge-2",
   "door",
   "forceps",
   "furnace",
   "grinder",
   "shield",
   "shield-2",
   "stairs",
   "stone-bridge",
   "stone-bridge-2",
   "wall-1",
   "wall-2",
   "wooden-platform",
   "wooden-platform-2"
  ]
 },
 {
  "slug": "isa-kitchen",
  "name": "isa-kitchen",
  "url": null,
  "models": [
   "canister-a-white",
   "canister-b-red",
   "canister-b-white",
   "chair",
   "cutting-board",
   "dishrack-plates",
   "door-modular",
   "kettle",
   "knife",
   "lid",
   "mug-ivory",
   "mug-taupe",
   "mug-terracotta",
   "pan",
   "plate",
   "pot",
   "spatula",
   "spoon",
   "utensil-crock",
   "wall-shelf",
   "wall-shelf-corner",
   "wall-shelf-hooks"
  ]
 },
 {
  "slug": "cooking-assets",
  "name": "cooking-assets",
  "url": null,
  "models": [
   "bread-knife",
   "butter-knife",
   "casserole-pot",
   "charcuterie-board",
   "chef-knife",
   "chopsticks",
   "cleaver",
   "cloche",
   "cooking-spoon",
   "crock-large",
   "cutting-board-a",
   "cutting-board-b",
   "dutch-oven",
   "fork",
   "frying-pan",
   "kettle",
   "ladle-a",
   "ladle-b",
   "mortar-and-pestle",
   "mug",
   "nakiri-knife",
   "paella-pan",
   "paring-knife",
   "plate-oval-small",
   "plate-rectangle",
   "platter-oval",
   "rice-paddle",
   "rolling-pin",
   "santoku-knife",
   "sauce-pan-large",
   "sauce-pan-small",
   "saute-pan",
   "serving-bowl",
   "skillet",
   "skillet-cast",
   "spatula",
   "spoon",
   "stock-pot",
   "strainer",
   "tankard",
   "teacup",
   "tongs",
   "tongs-open",
   "turner",
   "whisk",
   "wooden-paddle"
  ]
 },
 {
  "slug": "asia-rg",
  "name": "asia-rg",
  "url": null,
  "models": [
   "bamboo",
   "banner",
   "boat",
   "bowl",
   "bowl-shard",
   "cart",
   "cauldron",
   "coin",
   "dojo",
   "dragon-ornament",
   "drum",
   "fan",
   "fence-rail-a",
   "fence-rail-b",
   "fence-rope-a",
   "fence-rope-b",
   "footbridge",
   "garden-wall-a",
   "garden-wall-b",
   "garden-wall-c",
   "garden-wall-corner",
   "garden-wall-d",
   "garden-wall-gate-a",
   "garden-wall-gate-b",
   "gate",
   "gazebo",
   "geisha-a",
   "geisha-b",
   "gong",
   "grass",
   "house-a",
   "house-b",
   "house-c",
   "house-d",
   "house-e",
   "house-f",
   "house-small",
   "katana",
   "kunai",
   "ladder",
   "lantern-paper-a",
   "lantern-paper-b",
   "lily",
   "naginata",
   "notice-board",
   "pagoda",
   "parasol",
   "platform-deck",
   "platform-stone",
   "platform-wood",
   "rake",
   "rampart-a",
   "rampart-b",
   "rampart-c",
   "rampart-corner",
   "rampart-d",
   "rampart-post",
   "reeds",
   "river-bridge",
   "rock-formation-a",
   "rock-formation-b",
   "rock-small",
   "rock-tall-a",
   "rock-tall-b",
   "rock-tall-c",
   "rope-bells",
   "sack-a",
   "sack-b",
   "shrine",
   "shuriken",
   "stairs",
   "stepping-stone-a",
   "stepping-stone-b",
   "stepping-stone-c",
   "stepping-stone-d",
   "stepping-stone-e",
   "stepping-stone-f",
   "stepping-stone-g",
   "stone-lantern",
   "stool",
   "table",
   "teapot",
   "token",
   "token-hanging",
   "torii",
   "training-dummy",
   "tree-bed",
   "vase",
   "walkway"
  ]
 },
 {
  "slug": "mek-tools",
  "name": "mek-tools",
  "url": null,
  "models": [
   "axe",
   "axe-double",
   "brush",
   "hammer-bar",
   "hammer-block",
   "hammer-pein",
   "hammer-square",
   "hammer-stepped",
   "hammer-wedge",
   "pickaxe",
   "saw-coarse",
   "saw-crosscut",
   "saw-large",
   "sword"
  ]
 },
 {
  "slug": "asia-grave",
  "name": "asia-grave",
  "url": null,
  "note": "Bronzip zonder licentiebestand en zonder maker; zie kits/workfiles/asia-grave/LICENSE.txt.",
  "models": [
   "arch-stone",
   "bones-a",
   "bones-b",
   "bones-pile",
   "coffin-a",
   "coffin-b",
   "column-medium",
   "column-short",
   "column-tall",
   "crate",
   "floor-tile-a",
   "floor-tile-b",
   "floor-tile-c",
   "floor-tile-d",
   "floor-tile-e",
   "iron-fence-bars",
   "iron-fence-broken",
   "iron-fence-large",
   "iron-fence-medium",
   "iron-fence-post-a",
   "iron-fence-post-b",
   "iron-fence-post-c",
   "iron-fence-run",
   "iron-fence-short",
   "lamppost",
   "statue-mourner",
   "stone-block",
   "tomb-a",
   "tomb-b",
   "tomb-obelisk",
   "tombstone-a",
   "tombstone-b",
   "tombstone-c",
   "tombstone-d",
   "tombstone-e"
  ]
 },
 {
  "slug": "quat-town",
  "name": "quat-town",
  "url": null,
  "note": "Bronzips zonder licentiebestand en zonder maker.",
  "models": [
   "archery-1-a",
   "archery-1-b",
   "archery-1-c",
   "archery-2-a",
   "archery-2-b",
   "archery-2-c",
   "barracks-1-a",
   "barracks-1-b",
   "barracks-1-c",
   "barracks-2-a",
   "barracks-2-b",
   "barracks-2-c",
   "dock-1",
   "farm-2-a",
   "farm-2-b",
   "farm-2-c",
   "farm-field-a",
   "farm-field-b",
   "farm-field-c",
   "house-1-1-a",
   "house-1-1-b",
   "house-1-1-c",
   "house-1-2-a",
   "house-1-2-b",
   "house-1-2-c",
   "house-1-3-a",
   "house-1-3-c",
   "house-2-1-a",
   "house-2-1-b",
   "house-2-1-c",
   "house-2-2-a",
   "house-2-2-b",
   "house-2-2-c",
   "house-2-3-a",
   "house-2-3-b",
   "house-2-3-c",
   "logs",
   "market-1-a",
   "market-1-b",
   "market-1-c",
   "market-2-a",
   "market-2-b",
   "market-2-c",
   "mine",
   "ore-gold-a",
   "ore-gold-b",
   "ore-gold-c",
   "pine-trees",
   "port-1-a",
   "port-1-b",
   "port-1-c",
   "port-2-a",
   "port-2-b",
   "rock-a",
   "rock-b",
   "rock-c",
   "rock-pebble",
   "storage-1-a",
   "storage-1-b",
   "storage-1-c",
   "storage-2-a",
   "storage-2-b",
   "storage-2-c",
   "stumps",
   "tower-house-2",
   "town-center-1-a",
   "town-center-1-b",
   "town-center-1-c",
   "town-center-2-a",
   "town-center-2-c",
   "trees",
   "wall-1",
   "wall-2",
   "wall-towers-1",
   "wall-towers-2",
   "wall-towers-door-1",
   "wall-towers-door-2",
   "wall-towers-gate-1",
   "wall-towers-gate-2",
   "watchtower-1-a",
   "watchtower-1-b",
   "watchtower-1-c",
   "watchtower-2-a",
   "watchtower-2-b",
   "watchtower-2-c",
   "windmill-1",
   "windmill-2",
   "wonder-1-a",
   "wonder-1-b",
   "wonder-1-c",
   "wonder-2-b",
   "wonder-2-c",
   "wonder-walls-1",
   "wonder-walls-2"
  ]
 },
 {
  "slug": "kay-dun-2",
  "name": "kay-dun-2",
  "url": "https://www.kaylousberg.com",
  "models": [
   "barrel-large",
   "barrel-large-decorated",
   "barrel-small",
   "barrel-small-stack",
   "bed-decorated",
   "bed-floor",
   "bed-frame",
   "bottle-a-brown",
   "bottle-a-green",
   "bottle-a-labeled-brown",
   "bottle-a-labeled-green",
   "bottle-b-brown",
   "bottle-b-green",
   "bottle-c-brown",
   "bottle-c-green",
   "box-small-decorated",
   "box-stacked",
   "candle",
   "candle-lit",
   "candle-melted",
   "candle-thin",
   "candle-thin-lit",
   "candle-triple",
   "ceiling-tile",
   "chair",
   "chest",
   "chest-gold",
   "coin",
   "coin-stack-large",
   "coin-stack-medium",
   "coin-stack-small",
   "column",
   "crates-stacked",
   "floor-dirt-large",
   "floor-dirt-large-rocky",
   "floor-dirt-small-a",
   "floor-dirt-small-b",
   "floor-dirt-small-c",
   "floor-dirt-small-corner",
   "floor-dirt-small-d",
   "floor-dirt-small-weeds",
   "floor-foundation-allsides",
   "floor-foundation-corner",
   "floor-foundation-diagonal-corner",
   "floor-foundation-front",
   "floor-foundation-front-and-back",
   "floor-foundation-front-and-sides",
   "floor-tile-big-grate-open",
   "floor-tile-big-spikes",
   "floor-tile-extralarge-grates-open",
   "floor-tile-grate-open",
   "floor-tile-large",
   "floor-tile-large-rocks",
   "floor-tile-small",
   "floor-tile-small-broken-a",
   "floor-tile-small-broken-b",
   "floor-tile-small-corner",
   "floor-tile-small-decorated",
   "floor-tile-small-weeds-a",
   "floor-tile-small-weeds-b",
   "floor-wood-large",
   "floor-wood-large-dark",
   "floor-wood-small",
   "floor-wood-small-dark",
   "keg",
   "keg-decorated",
   "key",
   "keyring",
   "keyring-hanging",
   "pillar",
   "plate",
   "plate-food-a",
   "plate-food-b",
   "plate-small",
   "rubble-half",
   "rubble-large",
   "shelf-large",
   "shelf-small",
   "shelf-small-candles",
   "shelves",
   "stairs",
   "stairs-long",
   "stairs-narrow",
   "stairs-wall-left",
   "stairs-wall-right",
   "stairs-walled",
   "stairs-wide",
   "stairs-wood",
   "stairs-wood-decorated",
   "stool",
   "table-long",
   "table-long-broken",
   "table-long-decorated-a",
   "table-long-decorated-c",
   "table-medium",
   "table-medium-broken",
   "table-medium-decorated-a",
   "table-small",
   "table-small-decorated-a",
   "table-small-decorated-b",
   "torch",
   "torch-lit",
   "torch-mounted",
   "trunk-large-c",
   "trunk-medium-c",
   "trunk-small-c",
   "wall",
   "wall-arched",
   "wall-archedwindow-gated",
   "wall-archedwindow-gated-scaffold",
   "wall-archedwindow-open",
   "wall-broken",
   "wall-corner",
   "wall-corner-gated",
   "wall-corner-scaffold",
   "wall-corner-small",
   "wall-cracked",
   "wall-crossing",
   "wall-doorway",
   "wall-doorway-scaffold",
   "wall-doorway-sides",
   "wall-doorway-tsplit",
   "wall-endcap",
   "wall-gated",
   "wall-half",
   "wall-half-endcap",
   "wall-half-endcap-sloped",
   "wall-open-scaffold",
   "wall-pillar",
   "wall-scaffold",
   "wall-shelves",
   "wall-sloped",
   "wall-tsplit",
   "wall-tsplit-sloped",
   "wall-window-closed",
   "wall-window-closed-scaffold",
   "wall-window-open",
   "wall-window-open-scaffold"
  ]
 },
 {
  "slug": "quat-dun-2",
  "name": "quat-dun-2",
  "url": "https://quaternius.com/packs/modulardungeon.html",
  "models": [
   "bag-coins",
   "bag-standing",
   "chest",
   "chest-gold",
   "crate",
   "pedestal-2",
   "statue-horse",
   "sword-wall-mount",
   "trapdoor",
   "trapdoor-open"
  ]
 },
 {
  "slug": "kay-dun-1",
  "name": "kay-dun-1",
  "url": "https://www.kaylousberg.com",
  "models": [
   "arrow",
   "artifact",
   "axe-common",
   "axe-double-common",
   "axe-double-rare",
   "axe-double-uncommon",
   "axe-rare",
   "axe-uncommon",
   "barrel",
   "barrel-dark",
   "bench",
   "book-a",
   "book-b",
   "book-c",
   "book-d",
   "book-e",
   "book-f",
   "book-open-a",
   "book-open-b",
   "bookcase",
   "bookcase-filled",
   "bookcase-wide",
   "bookcase-wide-broken",
   "bookcase-wide-filled",
   "bookcase-wide-filled-broken",
   "bricks",
   "bucket",
   "chair-rounded",
   "chest-common",
   "chest-common-empty",
   "chest-rare",
   "chest-rare-mimic-closed",
   "chest-top-common",
   "chest-top-rare",
   "chest-top-uncommon",
   "chest-uncommon",
   "chest-uncommon-closed",
   "coin-crown",
   "coins-large",
   "coins-medium",
   "coins-small",
   "crate-dark",
   "crate-platform-large",
   "crossbow-common",
   "crossbow-rare",
   "crossbow-uncommon",
   "dagger-common",
   "dagger-rare",
   "dagger-uncommon",
   "door",
   "door-gate",
   "floor-decoration-shattered-bricks",
   "floor-decoration-tiles-large",
   "floor-decoration-tiles-small",
   "floor-decoration-wood",
   "floor-decoration-wood-left",
   "floor-decoration-wood-right",
   "hammer-common",
   "hammer-rare",
   "hammer-uncommon",
   "loot-sack-a",
   "loot-sack-b",
   "mug",
   "pillar-broken",
   "plate-full",
   "plate-half",
   "plate-rounded",
   "plate-stack",
   "pot-a",
   "pot-a-decorated",
   "pot-b",
   "pot-b-decorated",
   "pot-c",
   "pot-c-decorated",
   "potion-large-green",
   "potion-large-red",
   "potion-medium-green",
   "potion-medium-red",
   "potion-small-green",
   "potion-small-red",
   "pots",
   "quiver-empty",
   "quiver-full",
   "quiver-half-full",
   "scaffold-high",
   "scaffold-high-corner-both",
   "scaffold-high-corner-left",
   "scaffold-high-corner-right",
   "scaffold-high-railing",
   "scaffold-low",
   "scaffold-low-corner-both",
   "scaffold-low-corner-left",
   "scaffold-low-corner-right",
   "scaffold-low-railing",
   "scaffold-medium",
   "scaffold-medium-corner-both",
   "scaffold-medium-corner-left",
   "scaffold-medium-corner-right",
   "scaffold-medium-railing",
   "scaffold-small-high",
   "scaffold-small-high-corner-left",
   "scaffold-small-high-corner-right",
   "scaffold-small-high-long",
   "scaffold-small-high-railing",
   "scaffold-small-high-railing-long",
   "scaffold-small-low",
   "scaffold-small-low-corner-left",
   "scaffold-small-low-corner-right",
   "scaffold-small-low-long",
   "scaffold-small-low-railing",
   "scaffold-small-low-railing-long",
   "scaffold-small-medium",
   "scaffold-small-medium-corner-left",
   "scaffold-small-medium-corner-right",
   "scaffold-small-medium-long",
   "scaffold-small-medium-railing",
   "scaffold-small-medium-railing-long",
   "scaffold-stairs",
   "shield-common",
   "shield-rare",
   "shield-uncommon",
   "spell-book",
   "staff-common",
   "staff-rare",
   "staff-uncommon",
   "stool-rounded",
   "sword-common",
   "sword-rare",
   "sword-uncommon",
   "table-large",
   "table-medium-rounded",
   "table-small-rounded",
   "tile-brick-a-large",
   "tile-brick-b-large",
   "torch",
   "torch-wall",
   "trapdoor",
   "weapon-rack"
  ]
 },
 {
  "slug": "quat-dun-1",
  "name": "quat-dun-1",
  "url": "https://quaternius.com/packs/modulardungeon.html",
  "models": [
   "arch",
   "arch-door",
   "bucket",
   "cobweb",
   "cobweb-2",
   "column",
   "floor-bricks-separate",
   "floor-modular",
   "skull",
   "stairs-modular",
   "stairs-side-cover",
   "stairs-side-cover-wall",
   "wall-cover-modular",
   "wall-modular"
  ]
 },
 {
  "slug": "quat-blood-ring",
  "name": "quat-blood-ring",
  "url": "https://quaternius.com/",
  "models": [
   "blood-ring"
  ]
 },
 {
  "slug": "quat-skeleton",
  "name": "quat-skeleton",
  "url": "https://quaternius.com/",
  "models": [
   "skeleton"
  ]
 },
 {
  "slug": "kay-skeleton-1",
  "name": "kay-skeleton-1",
  "url": "https://www.kaylousberg.com",
  "models": [
   "bone",
   "bone-half",
   "bow",
   "helmet-horned",
   "helmet-horned-full",
   "hood",
   "hood-masked",
   "mage-cloak",
   "mage-cowl",
   "quiver-b",
   "ribcage-broken",
   "shield-round",
   "shield-round-arrows",
   "skull",
   "skull-broken",
   "spellbook",
   "staff-gem",
   "staff-gem-broken",
   "sword-broken",
   "sword-broken-half"
  ]
 },
 {
  "slug": "asia-pack",
  "name": "asia-pack",
  "url": null,
  "note": "Bronzip zonder licentiebestand en zonder maker; zie kits/workfiles/asia-pack/LICENSE.txt.",
  "models": [
   "altar-a",
   "altar-b",
   "arch-beam",
   "bamboo-a",
   "bamboo-b",
   "bamboo-c",
   "barrel-a",
   "barrel-b",
   "bell",
   "brazier",
   "bridge-stone",
   "bridge-wood",
   "cart",
   "clover",
   "door-left",
   "door-right",
   "drum",
   "egg",
   "fence-a",
   "fence-b",
   "fence-corner",
   "forge",
   "frame-wood",
   "garden-wall-a",
   "garden-wall-b",
   "garden-wall-c",
   "garden-wall-d",
   "garden-wall-e",
   "gong",
   "granary",
   "grave-a",
   "grave-b",
   "grave-c",
   "grave-d",
   "gravel-a",
   "gravel-b",
   "gravel-c",
   "graves-a",
   "graves-b",
   "hive",
   "house-a",
   "house-b",
   "house-c",
   "market-house",
   "market-stand",
   "nest",
   "net",
   "ore-gold",
   "ore-jade",
   "pillar-a",
   "pillar-a-tall",
   "pillar-b",
   "pillar-b-tall",
   "pillar-c",
   "pillar-c-tall",
   "pillar-wood",
   "plank-a",
   "plank-b",
   "plank-c",
   "plank-d",
   "plant-a",
   "plant-b",
   "plant-c",
   "plant-d",
   "platform-stone",
   "post-a",
   "post-b",
   "pot-large",
   "pot-small",
   "rock-block-a",
   "rock-block-b",
   "rock-block-c",
   "rock-large-a",
   "rock-large-b",
   "rock-large-c",
   "rock-medium-a",
   "rock-medium-b",
   "rock-medium-c",
   "rock-medium-d",
   "rock-small-a",
   "rock-small-b",
   "rock-small-c",
   "rock-small-d",
   "rock-small-e",
   "roof-pagoda",
   "shrine-large",
   "shrine-small",
   "statue-frog",
   "statue-monk",
   "steps-stone",
   "stone-lantern",
   "torii",
   "tower",
   "training-post",
   "tree-garden",
   "urn-a",
   "urn-b",
   "wall-decor-a",
   "wall-decor-b",
   "wall-decor-c",
   "wall-decor-d",
   "waterwheel",
   "well"
  ]
 },
 {
  "slug": "architecture",
  "name": "architecture",
  "url": null,
  "note": "Bronzip zonder licentiebestand en zonder maker.",
  "models": [
   "arch",
   "barn",
   "cabin",
   "castle",
   "church",
   "cottage",
   "ferris-wheel",
   "fortress"
  ]
 },
 {
  "slug": "asia-rocks",
  "name": "asia-rocks",
  "url": null,
  "note": "Bronzip zonder licentiebestand en zonder maker; zie kits/workfiles/asia-rocks/LICENSE.txt.",
  "models": [
   "boulder-a",
   "boulder-b",
   "boulder-c",
   "boulder-d",
   "boulder-e"
  ]
 },
 {
  "slug": "kay-mixed",
  "name": "kay-mixed",
  "url": "https://www.kaylousberg.com",
  "models": [
   "chain-anchor",
   "chain-hanging-a",
   "chain-hanging-b",
   "chain-link",
   "chain-links",
   "circus-tent",
   "comic-book",
   "comic-book-blank",
   "comic-books-stacked",
   "comic-box-closed",
   "comic-box-filled",
   "comic-box-open",
   "fire-hydrant",
   "flax-flower-a",
   "flax-flower-b",
   "guitar-a",
   "guitar-b",
   "idol-a",
   "idol-b",
   "instant-camera-a",
   "instant-camera-b",
   "mining-helmet",
   "photo-a",
   "photo-b",
   "plushie-chicken-a",
   "plushie-chicken-b",
   "puzzle-cube",
   "puzzle-cube-core",
   "puzzle-cube-scrambled",
   "rollerskate-a",
   "rollerskate-b",
   "rollerskate-pair",
   "shackle",
   "taco",
   "umbrella-a",
   "umbrella-b",
   "umbrella-c",
   "umbrella-d",
   "water-bottle-a",
   "water-bottle-b",
   "wood-stove"
  ]
 },
 {
  "slug": "kay-spook",
  "name": "kay-spook",
  "url": "https://www.kaylousberg.com",
  "models": [
   "branches",
   "candle-bundle",
   "candle-large",
   "candle-small",
   "candy-a",
   "candy-b",
   "cauldron",
   "coffin-a",
   "coffin-a-lid",
   "coffin-b",
   "coffin-b-lid",
   "fence",
   "fence-corner",
   "fence-double",
   "fence-post",
   "fence-single",
   "gravestone",
   "jack",
   "jackolantern-large",
   "jackolantern-small",
   "path-cobbled",
   "pumpkin-large",
   "pumpkin-small",
   "shrine",
   "tree-dead-a",
   "tree-dead-b",
   "tree-dead-c",
   "tree-dead-d"
  ]
 },

 {
  "slug": "kay-builder",
  "name": "kay-builder",
  "url": "https://www.kaylousberg.com",
  "models": [
   "archery-range",
   "barracks",
   "bridge",
   "bridge-roofed",
   "castle",
   "farm-plot",
   "forest",
   "forest-detail-a",
   "forest-detail-b",
   "house",
   "lumbermill",
   "market",
   "mill",
   "mine",
   "mountain",
   "rocks",
   "rocks-small",
   "tree-a",
   "tree-b",
   "tree-c",
   "wall-corner",
   "wall-gate",
   "wall-gate-closed",
   "wall-hex-corner-a",
   "wall-hex-corner-b",
   "wall-straight",
   "watchtower",
   "watermill",
   "well"
  ]
 },



 {
  "slug": "fishing-village",
  "name": "fishing-village",
  "url": null,
  "note": "Bronzip zonder licentiebestand en zonder maker; zie kits/workfiles/fishing-village/LICENSE.txt.",
  "models": [
   "boat-oars",
   "boat-poles",
   "boat-rack",
   "jetty-a",
   "jetty-b",
   "jetty-deck",
   "mooring-post",
   "rail-fence-a",
   "rail-fence-b",
   "rope-fence-long",
   "rope-fence-medium",
   "rope-fence-short",
   "stilt-cabin"
  ]
 },
 {
  "slug": "medieval-village",
  "name": "medieval-village",
  "url": null,
  "note": "Bronzip zonder licentiebestand en zonder maker; zie kits/workfiles/medieval-village/LICENSE.txt.",
  "models": [
   "archery-target",
   "barrel",
   "barrel-ore",
   "barrel-tapped",
   "crate-a",
   "crate-b",
   "dynamite-crate",
   "dynamite-crate-open",
   "haystack",
   "haystack-forked",
   "house-a",
   "house-b",
   "market-stall-green",
   "market-stall-red",
   "mine-entrance",
   "minecart",
   "minecart-ore",
   "picket-fence-a",
   "picket-fence-b",
   "picket-fence-c",
   "picket-fence-leaning",
   "rail-curve",
   "rail-long",
   "rail-short",
   "rail-straight",
   "rock-a",
   "rock-b",
   "sawmill",
   "silo",
   "smithy",
   "weapon-shop",
   "windmill",
   "wizard-tower"
  ]
 },
 {
  "slug": "village",
  "name": "village",
  "url": null,
  "note": "Bronzip zonder licentiebestand en zonder maker; zie kits/workfiles/village/LICENSE.txt.",
  "models": [
   "bridge-arched-a",
   "bridge-arched-b",
   "granary-large",
   "house-a",
   "house-b",
   "house-c"
  ]
 },
 {
  "slug": "arena-pack",
  "name": "arena-pack",
  "url": null,
  "note": "Bronzip zonder licentiebestand en zonder maker; zie kits/workfiles/arena-pack/LICENSE.txt.",
  "models": [
   "grass-tuft",
   "grass-tufts"
  ]
 },
 {
  "slug": "trees",
  "name": "trees",
  "url": null,
  "note": "Bronzip zonder licentiebestand en zonder maker; zie kits/workfiles/trees/LICENSE.txt.",
  "models": [
   "banana-tree",
   "cactus-flowering-round",
   "cactus-flowering-tall",
   "cactus-round",
   "cactus-tall",
   "dead-tree-a",
   "dead-tree-b",
   "dead-tree-c",
   "dead-tree-spiked-a",
   "dead-tree-spiked-b",
   "leafy-plant",
   "lilypad-a",
   "lilypad-b",
   "log-cut",
   "log-fallen",
   "palm-a",
   "palm-b",
   "palm-bent",
   "palm-young",
   "stump-a",
   "stump-b",
   "waterlilies-white",
   "waterlilies-yellow",
   "waterlily-white",
   "waterlily-yellow"
  ]
 },
 {
  "slug": "farm-buildings",
  "name": "farm-buildings",
  "url": null,
  "note": "Source zip with no licence file and no author named; see kits/workfiles/farm-buildings/LICENSE.txt.",
  "models": [
   "barn",
   "barn-large",
   "barn-open",
   "barn-small",
   "chicken-coop",
   "picket-fence",
   "rail-fence",
   "silo",
   "silo-house",
   "windmill"
  ]
 },
 {
  "slug": "toon-shooter",
  "name": "toon-shooter",
  "url": null,
  "note": "Source zip with no licence file and no author named; see kits/workfiles/toon-shooter/LICENSE.txt.",
  "models": [
   "bear-trap",
   "carbine",
   "cardboard-box",
   "cardboard-box-flat",
   "cardboard-boxes-a",
   "cardboard-boxes-b",
   "crate",
   "key",
   "knife-bowie",
   "knife-combat",
   "pallet",
   "pallet-broken",
   "planks",
   "revolver",
   "revolver-short",
   "sandbags",
   "sandbags-small",
   "shotgun",
   "sofa",
   "sofa-small",
   "tree-a",
   "tree-b",
   "tree-c",
   "tree-d"
  ]
 },
 {
  "slug": "ultimate-guns",
  "name": "ultimate-guns",
  "url": null,
  "note": "Source zip with no licence file and no author named; see kits/workfiles/ultimate-guns/LICENSE.txt.",
  "models": [
   "revolver",
   "revolver-ribbed",
   "revolver-steel",
   "shotgun",
   "shotgun-pistol-grip",
   "shotgun-pump",
   "shotgun-sawed-off"
  ]
 },
 {
  "slug": "isa-picnic",
  "name": "isa-picnic",
  "url": "https://www.isalousberg.com",
  "models": [
   "apple",
   "apple-cut",
   "apple-piece",
   "basket-round",
   "basket-square",
   "bowl",
   "cheese-wedge",
   "cheese-wheel",
   "fork",
   "grapes",
   "grapes-bowl",
   "jam-jar",
   "knife",
   "mug",
   "picnic-blanket-hunter",
   "picnic-blanket-hunter-folded",
   "picnic-blanket-sienna",
   "picnic-blanket-sienna-folded",
   "pillow-large-hunter",
   "pillow-large-sienna",
   "pillow-small-hunter",
   "pillow-small-sienna",
   "plate",
   "plate-flower",
   "sandwich",
   "spoon",
   "teapot",
   "tray-round",
   "tray-square",
   "tray-square-handles",
   "wine-bottle",
   "wine-glass"
  ]
 },
 {
  "slug": "isa-playground",
  "name": "isa-playground",
  "url": "https://www.isalousberg.com",
  "models": [
   "bucket",
   "cart",
   "fence-corner",
   "fence-post",
   "fence-rails",
   "fence-rails-long",
   "fence-straight",
   "fence-straight-long",
   "fence-straight-long-open",
   "fence-straight-open",
   "picnic-table",
   "sandcastle-a",
   "sandcastle-b",
   "sandcastle-c",
   "shovel",
   "stepping-stump-large",
   "stepping-stump-medium",
   "stepping-stump-small",
   "stepping-stumps",
   "tree-large",
   "tree-small"
  ]
 },
 {
  "slug": "isa-bakery",
  "name": "isa-bakery",
  "url": "https://www.isalousberg.com",
  "models": [
   "basket-a",
   "basket-b",
   "bread",
   "chair",
   "cookie",
   "cookie-jar",
   "counter-closet-a-large",
   "counter-closet-a-small",
   "counter-closet-b-large",
   "counter-closet-b-small",
   "cream-puff",
   "dough-ball",
   "egg-camel",
   "egg-ivory",
   "flour-sack",
   "flour-sack-open",
   "mixing-bowl",
   "mug-ivory",
   "mug-ivory-stacked",
   "mug-taupe",
   "pastry-stand",
   "pastry-stand-covered",
   "pastry-stand-filled",
   "pastry-stand-tiered",
   "plate",
   "plate-stacked",
   "pretzel",
   "rolling-pin",
   "rug",
   "serving-tray",
   "table-round",
   "tin-a",
   "tin-b",
   "whisk"
  ]
 },
 {
  "slug": "kay-minigame",
  "name": "kay-minigame",
  "url": "https://www.kaylousberg.com",
  "models": [
   "arrow",
   "bomb",
   "bow",
   "cactus",
   "flag",
   "forest-detail",
   "pine",
   "plant-a",
   "plant-b",
   "rocks-a",
   "rocks-b",
   "star",
   "sword",
   "target",
   "target-stand"
  ]
 },
 {
  "slug": "post-apocalypse",
  "name": "post-apocalypse",
  "url": null,
  "note": "Source zip with no licence file and no author named; see kits/workfiles/post-apocalypse/LICENSE.txt.",
  "models": [
   "axe",
   "bat-barbed",
   "chest-hunter",
   "chest-sienna",
   "dog-pug",
   "dog-shepherd",
   "fire-hydrant",
   "knife",
   "pallet",
   "pallet-broken",
   "pipes",
   "shotgun",
   "spear",
   "survivor-lis",
   "survivor-matt",
   "survivor-sam",
   "survivor-shaun",
   "trash-bag",
   "trash-bags"
  ]
 }
]
