window.KENNEY_KITS = [
 {
  "slug": "survival-kit",
  "name": "Survival Kit",
  "url": "https://kenney.nl/assets/survival-kit",
  "models": [
   "bottle",
   "bottle-large",
   "campfire-fishing-stand",
   "campfire-pit",
   "campfire-stand",
   "chest",
   "fence",
   "fence-doorway",
   "fence-fortified",
   "fish",
   "fish-large",
   "floor",
   "floor-hole",
   "floor-old",
   "resource-planks",
   "resource-stone",
   "resource-stone-large",
   "rock-a",
   "rock-b",
   "rock-c",
   "rock-flat",
   "rock-flat-grass",
   "rock-sand-a",
   "rock-sand-b",
   "rock-sand-c",
   "signpost",
   "signpost-single",
   "structure",
   "structure-canvas",
   "structure-floor",
   "structure-roof",
   "tent",
   "tent-canvas",
   "tool-axe",
   "tool-hammer",
   "tool-hoe",
   "tool-pickaxe",
   "tool-shovel",
   "tree",
   "tree-log",
   "tree-log-small",
   "tree-tall",
   "workbench",
   "workbench-anvil",
   "workbench-grind"
  ]
 },
 {
  "slug": "pirate-kit",
  "name": "Pirate Kit",
  "url": "https://kenney.nl/assets/pirate-kit",
  "models": [
   "boat-row-large",
   "boat-row-small",
   "bottle",
   "bottle-large",
   "cannon",
   "cannon-ball",
   "cannon-mobile",
   "chest",
   "crate",
   "crate-bottles",
   "flag",
   "flag-high",
   "hole",
   "mast",
   "mast-ropes",
   "palm-detailed-bend",
   "palm-detailed-straight",
   "patch-grass",
   "patch-grass-foliage",
   "patch-sand",
   "patch-sand-foliage",
   "platform",
   "platform-planks",
   "rocks-a",
   "rocks-b",
   "rocks-c",
   "rocks-sand-a",
   "rocks-sand-b",
   "rocks-sand-c",
   "ship-ghost",
   "ship-large",
   "ship-medium",
   "ship-pirate-large",
   "ship-pirate-medium",
   "ship-pirate-small",
   "ship-small",
   "ship-wreck",
   "structure",
   "structure-fence",
   "structure-fence-sides",
   "structure-platform",
   "structure-platform-dock",
   "structure-platform-dock-small",
   "structure-platform-small",
   "structure-roof",
   "tool-paddle"
  ]
 },
 {
  "slug": "modular-cave-kit",
  "name": "Modular Cave Kit",
  "url": "https://kenney.nl/assets/modular-cave-kit",
  "buitenCatalogus": [
   "corridor", "corridor-corner", "corridor-end", "corridor-intersection", "corridor-junction",
   "corridor-transition", "corridor-wide", "corridor-wide-corner", "corridor-wide-end",
   "corridor-wide-intersection", "corridor-wide-junction", "gate", "gate-metal-bars",
   "gate-overhang", "gate-rock", "room-corner", "room-large", "room-large-variation",
   "room-small", "room-small-variation", "room-wide", "room-wide-variation", "stairs",
   "stairs-wide", "template-corner", "template-detail", "template-floor", "template-floor-big",
   "template-floor-detail", "template-floor-detail-a", "template-wall", "template-wall-corner",
   "template-wall-detail-a", "template-wall-half", "template-wall-stairs", "template-wall-top"
  ],
  "toelichting": "Staat op zichzelf: eigen texture-atlas en eigen kleuren, gedeeld met geen enkele andere kit. Daarom een eigen tabblad — deze modellen zijn niet uitwisselbaar met die van de andere kits.",
  "models": [
   "corridor",
   "corridor-corner",
   "corridor-end",
   "corridor-intersection",
   "corridor-junction",
   "corridor-transition",
   "corridor-wide",
   "corridor-wide-corner",
   "corridor-wide-end",
   "corridor-wide-intersection",
   "corridor-wide-junction",
   "gate",
   "gate-metal-bars",
   "gate-overhang",
   "gate-rock",
   "ladder",
   "room-corner",
   "room-large",
   "room-large-variation",
   "room-small",
   "room-small-variation",
   "room-wide",
   "room-wide-variation",
   "stairs",
   "stairs-wide",
   "template-corner",
   "template-detail",
   "template-floor",
   "template-floor-big",
   "template-floor-detail",
   "template-floor-detail-a",
   "template-floor-layer",
   "template-floor-layer-hole",
   "template-floor-layer-raised",
   "template-wall",
   "template-wall-corner",
   "template-wall-detail-a",
   "template-wall-half",
   "template-wall-stairs",
   "template-wall-top"
  ]
 },
 {
  "slug": "mini-forest",
  "name": "Mini Forest",
  "url": "https://kenney.nl/assets/mini-forest",
  "models": [
   "bridge",
   "building-structure",
   "ladder",
   "patch-dirt",
   "patch-grass",
   "stones",
   "target",
   "tree",
   "tree-high"
  ]
 },
 {
  "slug": "fantasy-town-kit",
  "name": "Fantasy Town Kit",
  "url": "https://kenney.nl/assets/fantasy-town-kit",
  "models": [
   "balcony-wall",
   "balcony-wall-fence",
   "banner-green",
   "banner-red",
   "blade",
   "cart",
   "cart-high",
   "fence",
   "fence-broken",
   "fence-curved",
   "fence-gate",
   "overhang",
   "pillar-wood",
   "planks",
   "planks-half",
   "planks-opening",
   "poles",
   "poles-horizontal",
   "rock-large",
   "rock-small",
   "rock-wide",
   "roof-corner",
   "roof-corner-inner",
   "roof-corner-round",
   "roof-flat",
   "roof-gable-detail",
   "roof-gable-end",
   "roof-gable-top",
   "roof-left",
   "roof-point",
   "roof-right",
   "roof-window",
   "stairs-stone-corner",
   "stairs-stone-round",
   "stairs-wide-wood",
   "stairs-wide-wood-handrail",
   "stairs-wood",
   "stairs-wood-handrail",
   "tree",
   "tree-crooked",
   "tree-high",
   "tree-high-crooked",
   "tree-high-round",
   "wall-wood",
   "wall-wood-arch",
   "wall-wood-arch-top",
   "wall-wood-block",
   "wall-wood-block-half",
   "wall-wood-broken",
   "wall-wood-corner",
   "wall-wood-corner-diagonal",
   "wall-wood-corner-diagonal-half",
   "wall-wood-corner-edge",
   "wall-wood-detail-cross",
   "wall-wood-detail-diagonal",
   "wall-wood-detail-horizontal",
   "wall-wood-diagonal",
   "wall-wood-door",
   "wall-wood-doorway-base",
   "wall-wood-doorway-square",
   "wall-wood-doorway-square-wide-curved",
   "wall-wood-half",
   "wall-wood-side",
   "wall-wood-window-glass",
   "wall-wood-window-round",
   "wall-wood-window-shutters",
   "watermill",
   "watermill-wide",
   "wheel",
   "windmill"
  ]
 },
 {
  "slug": "platformer-kit",
  "name": "Platformer Kit",
  "url": "https://kenney.nl/assets/platformer-kit",
  "models": [
   "arrow",
   "arrows",
   "crate",
   "crate-strong",
   "fence-broken",
   "fence-corner",
   "fence-corner-curved",
   "fence-rope",
   "fence-straight",
   "flowers",
   "flowers-tall",
   "heart",
   "ladder",
   "ladder-broken",
   "ladder-long",
   "lever",
   "lock",
   "mushrooms",
   "platform",
   "platform-fortified",
   "platform-overhang",
   "platform-ramp",
   "poles",
   "rocks",
   "sign",
   "spring",
   "star",
   "stones"
  ]
 },
 {
  "slug": "mini-dungeon",
  "name": "Mini Dungeon",
  "url": "https://kenney.nl/assets/mini-dungeon",
  "models": [
   "pot",
   "wood-structure",
   "wood-support"
  ]
 },
 {
  "slug": "onderwater-kit",
  "name": "Onderwater",
  "url": "https://quaternius.com/",
  "buitenCatalogus": true,
  "toelichting": "Staat op zichzelf: eigen materiaalkleuren in plaats van de gedeelde colormap. De dieren zijn gerigd en dragen hun eigen animaties — de enige geanimeerde modellen in de catalogus. Het grootste deel is een pack van Quaternius, ingeladen op een kwart van de oorspronkelijke maat zodat het op hetzelfde raster past als de rest. De orka en het orkakalf komen daar niet vandaan: die zijn zelf gebouwd (tools/bouw-orka.mjs), omdat de pack wel een walvis en twee haaien heeft maar geen orka.",
  "models": [
   "coral-a",
   "coral-b",
   "coral-c",
   "coral-d",
   "coral-e",
   "coral-f",
   "coral-g",
   "crab",
   "dolphin",
   "eel",
   "fish-brown",
   "fish-clown",
   "fish-dory",
   "fish-tuna",
   "lobster",
   "octopus",
   "orca",
   "orca-calf",
   "penguin",
   "rock-a",
   "rock-b",
   "rock-c",
   "rock-d",
   "rock-e",
   "rock-f",
   "rock-g",
   "rock-h",
   "rock-i",
   "rock-j",
   "rock-k",
   "sand-dollar",
   "seal",
   "seaweed-a",
   "seaweed-b",
   "seaweed-c",
   "shark",
   "shark-hammerhead",
   "shell-clam",
   "shell-scallop",
   "shell-spiral",
   "squid",
   "starfish",
   "stingray",
   "turtle",
   "whale"
  ]
 },
 {
  "slug": "taalei-kit",
  "name": "Taalei Kit",
  "url": null,
  "models": [
   "balloon",
   "lighthouse"
  ]
 },
 {
  "slug": "nature",
  "name": "Nature",
  "url": null,
  "models": [
   "branch-a",
   "mountain-a",
   "tree-dead"
  ]
 },
 {
  "slug": "tropical",
  "name": "Tropical",
  "url": null,
  "models": [
   "barrel-a",
   "chest-a",
   "palm-a",
   "plant-a"
  ]
 },
 {
  "slug": "props",
  "name": "Props",
  "url": null,
  "models": [
   "bag-a",
   "barrel-a",
   "bench-a",
   "bottle-a",
   "bottle-b",
   "bottle-c",
   "box-a",
   "bucket-a",
   "carpet-a",
   "cup-a",
   "fire-a",
   "firewood-a",
   "jug-a",
   "jug-b",
   "jug-c",
   "jug-d",
   "meat-leg-a",
   "mushroom-a",
   "plate-b",
   "plate-c",
   "roast-a",
   "stairs-a",
   "stool-a",
   "table-a"
  ]
 },
 {
  "slug": "rocks",
  "name": "Rocks",
  "url": null,
  "models": [
   "debris-a",
   "debris-b",
   "pebbles-dirt-a",
   "pebbles-dirt-b",
   "pebbles-dirt-c",
   "pebbles-dirt-d",
   "rock-natural-a",
   "rock-natural-b",
   "rock-natural-c",
   "rock-natural-d",
   "rock-natural-e",
   "rock-natural-f",
   "rock-natural-g",
   "rock-natural-h",
   "rock-natural-i",
   "rock-natural-j",
   "rockform-arch",
   "rockform-column",
   "rockform-corner-hard",
   "rockform-corner-soft",
   "rockform-wall-long",
   "rockform-wall-short-a",
   "rockform-wall-short-b",
   "rockwall-corner",
   "rockwall-straight"
  ]
 },
 {
  "slug": "village-kit",
  "name": "Modular Village",
  "url": null,
  "models": [
   "barrel-a",
   "barrel-a-open",
   "barrel-b",
   "bell-a",
   "boat-a",
   "boat-b",
   "boat-oars-a",
   "boat-oars-b",
   "canopy-beam",
   "canopy-beam-short",
   "canopy-corner",
   "canopy-full",
   "canopy-ramp-corner",
   "canopy-ramp-full",
   "canopy-ramp-mid",
   "canopy-side",
   "canopy-sides-opposite",
   "canopy-top",
   "cart-a",
   "chimney-pipe",
   "cobblestone-dirt-transition-a",
   "cobblestone-dirt-transition-b",
   "cobblestone-dirt-transition-c",
   "cobblestone-dirt-transition-d",
   "cobblestone-floor-a",
   "crate-a",
   "crate-a-open",
   "dirt-fading",
   "dirt-fading-gathered",
   "dirt-gathered-corner",
   "dirt-gathered-straight",
   "door-ornate",
   "door-simple",
   "ladder-a",
   "lamp-street",
   "lamp-wall",
   "roof-accent-rake-concave",
   "roof-accent-rake-convex",
   "roof-accent-rake-eave",
   "roof-accent-rake-straight",
   "roof-accent-ridge",
   "roof-accent-ridge-end",
   "roof-concave-corner-inner",
   "roof-concave-corner-outer",
   "roof-concave-corner-outer-eave",
   "roof-concave-side",
   "roof-concave-side-eave",
   "roof-concave-side-eave-edge",
   "roof-concave-side-edge",
   "roof-convex-corner-inner",
   "roof-convex-corner-outer",
   "roof-convex-corner-outer-eave",
   "roof-convex-side",
   "roof-convex-side-eave",
   "roof-convex-side-eave-edge",
   "roof-convex-side-edge",
   "roof-straight-corner-inner",
   "roof-straight-corner-outer",
   "roof-straight-corner-outer-eave",
   "roof-straight-side",
   "roof-straight-side-eave",
   "roof-straight-side-eave-edge",
   "roof-straight-side-edge",
   "sign-a",
   "stone-arch",
   "stone-curb-a",
   "stone-curb-b",
   "stone-curb-c",
   "stone-curb-d",
   "stone-doorway-narrow-tall-a",
   "stone-doorway-narrow-tall-b",
   "stone-doorway-wide-tall-a",
   "stone-doorway-wide-tall-b",
   "stone-stucco-doorway-wide-tall-a",
   "stone-stucco-doorway-wide-tall-b",
   "stone-wall-a",
   "stone-wall-b",
   "stone-wall-c",
   "stone-wall-d",
   "stone-wall-e",
   "stucco-arch-half",
   "stucco-arch-half-outer",
   "stucco-block",
   "stucco-doorway-narrow-tall",
   "stucco-doorway-wide-tall",
   "stucco-support-angled-large",
   "stucco-support-angled-low",
   "stucco-support-angled-small",
   "stucco-support-beam-a",
   "stucco-support-beam-b",
   "stucco-support-beam-c",
   "stucco-support-pillar-a",
   "stucco-support-pillar-b",
   "stucco-support-pillar-c",
   "stucco-window-double-narrow",
   "stucco-window-double-narrow-tall",
   "stucco-window-double-wide",
   "stucco-window-double-wide-tall",
   "stucco-window-rounded-narrow",
   "stucco-window-rounded-narrow-tall",
   "stucco-window-rounded-wide",
   "stucco-window-rounded-wide-tall",
   "stucco-window-single-narrow",
   "stucco-window-single-narrow-tall",
   "stucco-window-single-wide",
   "stucco-window-single-wide-tall",
   "waterwheel",
   "waterwheel-flume-brace",
   "waterwheel-flume-brace-double",
   "waterwheel-flume-end",
   "waterwheel-flume-pillar",
   "waterwheel-flume-ramp",
   "waterwheel-flume-ramp-supported",
   "waterwheel-flume-straight",
   "well-a",
   "well-base-cobblestone",
   "well-base-dirt",
   "well-base-grass",
   "well-inside",
   "windmill-blades",
   "window-upper-straight",
   "wood-baseboard",
   "wood-floor-corner",
   "wood-floor-straight-a",
   "wood-floor-straight-b",
   "wood-floor-straight-c",
   "wood-floor-straight-d",
   "wood-post-large",
   "wood-post-small",
   "wood-railing-corner",
   "wood-railing-stairs",
   "wood-railing-straight",
   "wood-rope-corner",
   "wood-rope-stairs",
   "wood-rope-straight",
   "wood-steps",
   "wood-steps-stucco"
  ]
 },
 {
  "slug": "rpgtools",
  "name": "RPG Tools",
  "url": "https://www.kaylousberg.com",
  "models": [
   "anvil",
   "axe",
   "chisel",
   "compass-base",
   "drafting-compass",
   "file",
   "grindstone",
   "hammer",
   "handdrill",
   "handplane",
   "journal-closed",
   "journal-open",
   "knife",
   "lantern",
   "magnifying-glass",
   "mallet",
   "map-empty",
   "map-rolled",
   "nail",
   "pencil-a-long",
   "pencil-b-long",
   "pickaxe",
   "rope-bundle-a",
   "rope-bundle-b",
   "saw",
   "scissors",
   "screw-b",
   "screwdriver-a-short",
   "screwdriver-b-short",
   "shovel",
   "tongs",
   "torch",
   "torch-burnt",
   "trowel",
   "wrench-b"
  ]
 },
 {
  "slug": "forest",
  "name": "Forest",
  "url": "https://www.kaylousberg.com",
  "models": [
   "grass-1-a",
   "grass-1-b",
   "grass-1-c",
   "grass-1-d",
   "grass-2-a",
   "grass-2-b",
   "grass-2-c",
   "grass-2-d",
   "rock-1-a",
   "rock-1-b",
   "rock-1-c",
   "rock-1-d",
   "rock-1-e",
   "rock-1-f",
   "rock-1-g",
   "rock-1-h",
   "rock-1-i",
   "rock-1-j",
   "rock-1-k",
   "rock-1-l",
   "rock-1-m",
   "rock-1-n",
   "rock-1-o",
   "rock-1-p",
   "rock-1-q",
   "rock-2-a",
   "rock-2-b",
   "rock-2-c",
   "rock-2-d",
   "rock-2-e",
   "rock-2-f",
   "rock-2-g",
   "rock-2-h",
   "rock-3-a",
   "rock-3-b",
   "rock-3-c",
   "rock-3-d",
   "rock-3-e",
   "rock-3-f",
   "rock-3-g",
   "rock-3-h",
   "rock-3-i",
   "rock-3-j",
   "rock-3-k",
   "rock-3-l",
   "rock-3-m",
   "rock-3-n",
   "rock-3-o",
   "rock-3-p",
   "rock-3-q",
   "rock-3-r",
   "tree-bare-1-a",
   "tree-bare-1-b",
   "tree-bare-1-c",
   "tree-bare-2-a",
   "tree-bare-2-b",
   "tree-bare-2-c"
  ]
 },
 {
  "slug": "resources",
  "name": "Resources",
  "url": "https://www.kaylousberg.com",
  "models": [
   "copper-bar",
   "copper-bars",
   "copper-bars-stack-large",
   "copper-bars-stack-medium",
   "copper-bars-stack-small",
   "copper-nugget-large",
   "copper-nugget-medium",
   "copper-nugget-small",
   "copper-nuggets",
   "gold-bar",
   "gold-bars",
   "gold-bars-stack-large",
   "gold-bars-stack-medium",
   "gold-bars-stack-small",
   "gold-nugget-large",
   "gold-nugget-medium",
   "gold-nugget-small",
   "gold-nuggets",
   "iron-bar",
   "iron-bars",
   "iron-bars-stack-large",
   "iron-bars-stack-medium",
   "iron-bars-stack-small",
   "iron-nugget-large",
   "iron-nugget-medium",
   "iron-nugget-small",
   "iron-nuggets",
   "pallet-wood",
   "parts-pile-large",
   "parts-pile-medium",
   "parts-pile-small",
   "silver-bar",
   "silver-bars",
   "silver-bars-stack-large",
   "silver-bars-stack-medium",
   "silver-bars-stack-small",
   "silver-nugget-large",
   "silver-nugget-medium",
   "silver-nugget-small",
   "silver-nuggets",
   "stone-brick",
   "stone-bricks-stack-large",
   "stone-bricks-stack-medium",
   "stone-bricks-stack-small",
   "stone-chunks-large",
   "stone-chunks-small",
   "textiles-stack-large",
   "wood-log-a",
   "wood-log-b",
   "wood-log-stack",
   "wood-plank-a",
   "wood-plank-b",
   "wood-plank-c",
   "wood-planks-stack-large",
   "wood-planks-stack-medium",
   "wood-planks-stack-small"
  ]
 },
 {
  "slug": "dungeon",
  "name": "Dungeon",
  "url": "https://www.kaylousberg.com",
  "models": [
   "barrel-large",
   "barrel-large-decorated",
   "barrel-small",
   "barrel-small-stack",
   "bed-decorated",
   "bed-floor",
   "bed-frame",
   "bottle-a-brown",
   "bottle-a-labeled-brown",
   "bottle-b-brown",
   "bottle-c-brown",
   "box-large",
   "box-small",
   "box-small-decorated",
   "box-stacked",
   "candle",
   "candle-lit",
   "candle-melted",
   "candle-thin",
   "candle-thin-lit",
   "candle-triple",
   "ceiling-tile",
   "chair",
   "chest",
   "chest-gold",
   "coin",
   "coin-stack-large",
   "coin-stack-medium",
   "coin-stack-small",
   "column",
   "crates-stacked",
   "floor-dirt-large",
   "floor-dirt-large-rocky",
   "floor-dirt-small-a",
   "floor-dirt-small-b",
   "floor-dirt-small-c",
   "floor-dirt-small-d",
   "floor-dirt-small-corner",
   "floor-dirt-small-weeds",
   "floor-foundation-allsides",
   "floor-foundation-corner",
   "floor-foundation-diagonal-corner",
   "floor-foundation-front",
   "floor-foundation-front-and-back",
   "floor-foundation-front-and-sides",
   "floor-tile-big-grate-open",
   "floor-tile-big-spikes",
   "floor-tile-extralarge-grates-open",
   "floor-tile-grate-open",
   "floor-tile-large",
   "floor-tile-large-rocks",
   "floor-tile-small",
   "floor-tile-small-broken-a",
   "floor-tile-small-broken-b",
   "floor-tile-small-corner",
   "floor-tile-small-decorated",
   "floor-tile-small-weeds-a",
   "floor-tile-small-weeds-b",
   "floor-wood-large",
   "floor-wood-large-dark",
   "floor-wood-small",
   "floor-wood-small-dark",
   "keg",
   "keg-decorated",
   "key",
   "keyring",
   "keyring-hanging",
   "pillar",
   "plate",
   "plate-food-a",
   "plate-food-b",
   "plate-small",
   "rubble-half",
   "rubble-large",
   "shelf-large",
   "shelf-small",
   "shelf-small-candles",
   "shelves",
   "stairs",
   "stairs-long",
   "stairs-narrow",
   "stairs-wall-left",
   "stairs-wall-right",
   "stairs-walled",
   "stairs-wide",
   "stairs-wood",
   "stairs-wood-decorated",
   "stool",
   "table-long",
   "table-long-broken",
   "table-long-decorated-a",
   "table-long-decorated-c",
   "table-medium",
   "table-medium-broken",
   "table-medium-decorated-a",
   "table-small",
   "table-small-decorated-a",
   "table-small-decorated-b",
   "torch",
   "torch-lit",
   "torch-mounted",
   "trunk-large-c",
   "trunk-small-c",
   "wall",
   "wall-tsplit",
   "wall-tsplit-sloped",
   "wall-arched",
   "wall-archedwindow-gated",
   "wall-archedwindow-gated-scaffold",
   "wall-archedwindow-open",
   "wall-broken",
   "wall-corner",
   "wall-corner-gated",
   "wall-corner-scaffold",
   "wall-corner-small",
   "wall-cracked",
   "wall-crossing",
   "wall-doorway",
   "wall-doorway-tsplit",
   "wall-doorway-scaffold",
   "wall-doorway-sides",
   "wall-endcap",
   "wall-gated",
   "wall-half",
   "wall-half-endcap",
   "wall-half-endcap-sloped",
   "wall-open-scaffold",
   "wall-pillar",
   "wall-scaffold",
   "wall-shelves",
   "wall-sloped",
   "wall-window-closed",
   "wall-window-closed-scaffold",
   "wall-window-open",
   "wall-window-open-scaffold"
  ]
 },
 {
  "slug": "modulair-terrein",
  "name": "Modulair Terrein",
  "url": null,
  "buitenCatalogus": [
   "cave-prop-entrance", "cave-prop-minecart", "cave-prop-pick-large", "cave-prop-pick-small",
   "cave-prop-railway-bumpstop", "cave-prop-railway-curve-large",
   "cave-prop-railway-curve-small", "cave-prop-railway-hill-gentle",
   "cave-prop-railway-hill-sharp", "cave-prop-railway-intersection",
   "cave-prop-railway-straight-a", "cave-prop-railway-straight-b",
   "cave-prop-railway-straight-c", "cave-prop-railway-straight-d", "cave-prop-railway-switch",
   "cave-prop-stalagmite-connected-base", "cave-prop-stalagmite-connected-mid",
   "cave-prop-stalagmite-connected-top", "cave-prop-stalagmite-normal",
   "cave-prop-stalagmite-tiny", "cave-prop-support-ceiling-beam-a",
   "cave-prop-support-ceiling-beam-b", "cave-prop-support-ceiling-beam-c",
   "cave-prop-support-ceiling-beam-d", "cave-prop-support-ceiling-boards-a",
   "cave-prop-support-ceiling-boards-b", "cave-prop-support-ceiling-boards-c",
   "cave-prop-support-ceiling-boards-d", "cave-prop-support-corner-brace-a",
   "cave-prop-support-corner-brace-b", "cave-prop-support-wall-boards-a",
   "cave-prop-support-wall-boards-b", "cave-prop-support-wall-boards-c",
   "cave-prop-support-wall-boards-d", "cave-prop-support-wall-pillar-a",
   "cave-prop-support-wall-pillar-b", "cave-prop-support-wall-pillar-c",
   "cave-prop-support-wall-pillar-d"
  ],
  "models": [
   "beach-prop-coconut",
   "beach-prop-docks-corner",
   "beach-prop-docks-corner-supports",
   "beach-prop-docks-steps",
   "beach-prop-docks-straight",
   "beach-prop-docks-straight-supports",
   "beach-prop-shell-a",
   "beach-prop-shell-b",
   "beach-prop-starfish-a",
   "beach-prop-starfish-b",
   "beach-prop-treasure-chest",
   "beach-prop-tree-palm-a",
   "beach-prop-tree-palm-b",
   "beach-prop-tree-palm-c",
   "cave-prop-entrance",
   "cave-prop-minecart",
   "cave-prop-pick-large",
   "cave-prop-pick-small",
   "cave-prop-railway-bumpstop",
   "cave-prop-railway-curve-large",
   "cave-prop-railway-curve-small",
   "cave-prop-railway-hill-gentle",
   "cave-prop-railway-hill-sharp",
   "cave-prop-railway-intersection",
   "cave-prop-railway-straight-a",
   "cave-prop-railway-straight-b",
   "cave-prop-railway-straight-c",
   "cave-prop-railway-straight-d",
   "cave-prop-railway-switch",
   "cave-prop-stalagmite-connected-base",
   "cave-prop-stalagmite-connected-mid",
   "cave-prop-stalagmite-connected-top",
   "cave-prop-stalagmite-normal",
   "cave-prop-stalagmite-tiny",
   "cave-prop-support-ceiling-beam-a",
   "cave-prop-support-ceiling-beam-b",
   "cave-prop-support-ceiling-beam-c",
   "cave-prop-support-ceiling-beam-d",
   "cave-prop-support-ceiling-boards-a",
   "cave-prop-support-ceiling-boards-b",
   "cave-prop-support-ceiling-boards-c",
   "cave-prop-support-ceiling-boards-d",
   "cave-prop-support-corner-brace-a",
   "cave-prop-support-corner-brace-b",
   "cave-prop-support-wall-boards-a",
   "cave-prop-support-wall-boards-b",
   "cave-prop-support-wall-boards-c",
   "cave-prop-support-wall-boards-d",
   "cave-prop-support-wall-pillar-a",
   "cave-prop-support-wall-pillar-b",
   "cave-prop-support-wall-pillar-c",
   "cave-prop-support-wall-pillar-d",
   "cliff-prop-bridge-rope-end",
   "hilly-prop-branch-a",
   "hilly-prop-branch-b",
   "hilly-prop-branch-c",
   "hilly-prop-camp-campfire",
   "hilly-prop-camp-wood-pile",
   "hilly-prop-cattail-a",
   "hilly-prop-cattail-b",
   "hilly-prop-fence-boards-a",
   "hilly-prop-fence-boards-b",
   "hilly-prop-fence-boards-c",
   "hilly-prop-fence-boards-d",
   "hilly-prop-fence-curve-1x1",
   "hilly-prop-fence-curve-2x2",
   "hilly-prop-fence-curve-3x3",
   "hilly-prop-fence-gate-a",
   "hilly-prop-fence-gate-b",
   "hilly-prop-fence-hill-gentle",
   "hilly-prop-fence-hill-sharp",
   "hilly-prop-fence-post-a",
   "hilly-prop-fence-post-b",
   "hilly-prop-fence-post-c",
   "hilly-prop-fence-post-d",
   "hilly-prop-flower-daisy",
   "hilly-prop-flower-lily-blue",
   "hilly-prop-flower-lily-pink",
   "hilly-prop-flower-rose",
   "hilly-prop-flower-sunflower",
   "hilly-prop-flower-tulip",
   "hilly-prop-grass-clump-a",
   "hilly-prop-grass-clump-b",
   "hilly-prop-grass-clump-c",
   "hilly-prop-grass-clump-d",
   "hilly-prop-mushroom-a",
   "hilly-prop-mushroom-b",
   "hilly-prop-rock-a",
   "hilly-prop-rock-b",
   "hilly-prop-rock-c",
   "hilly-prop-rock-d",
   "hilly-prop-stepping-stones-a",
   "hilly-prop-stepping-stones-b",
   "hilly-prop-stepping-stones-c",
   "hilly-prop-stepping-stones-d",
   "hilly-prop-stepping-stones-e",
   "hilly-prop-stepping-stones-f",
   "hilly-prop-stepping-stones-g",
   "hilly-prop-stepping-stones-h",
   "hilly-prop-stump",
   "hilly-prop-tree-cedar-a",
   "hilly-prop-tree-cedar-b",
   "hilly-prop-tree-pine-a",
   "hilly-prop-tree-pine-b",
   "hilly-prop-tree-pine-c",
   "mountain-a",
   "mountain-b",
   "mountain-c",
   "mountain-d",
   "shared-prop-boulder-a",
   "shared-prop-boulder-b",
   "shared-prop-boulder-c",
   "shared-prop-boulder-d",
   "shared-prop-boulder-e",
   "shared-prop-boulder-f"
  ]
 },
 {
  "slug": "castle-kit",
  "name": "Castle Kit",
  "url": "https://kenney.nl/assets/castle-kit",
  "models": [
   "flag",
   "flag-pennant",
   "flag-wide",
   "rocks-large",
   "rocks-small",
   "tower-square-mid-open",
   "tower-square-mid-open-simple",
   "tree-large",
   "tree-log",
   "tree-small",
   "tree-trunk"
  ]
 },
 {
  "slug": "graveyard-kit",
  "name": "Graveyard Kit",
  "url": "https://kenney.nl/assets/graveyard-kit",
  "models": [
   "debris",
   "debris-wood",
   "detail-bowl",
   "detail-chalice",
   "detail-plate",
   "pine",
   "pine-fall",
   "rocks",
   "rocks-tall",
   "shovel",
   "shovel-dirt"
  ]
 },
 {
  "slug": "holiday-kit",
  "name": "Holiday Kit",
  "url": "https://kenney.nl/assets/holiday-kit",
  "models": [
   "lantern",
   "lantern-hanging",
   "rocks-large",
   "rocks-medium",
   "rocks-small",
   "snow-bunker",
   "snow-flat",
   "snow-flat-large",
   "snow-pile",
   "snowman",
   "snowman-hat",
   "tree",
   "tree-snow-a",
   "tree-snow-b",
   "tree-snow-c"
  ]
 },
 {
  "slug": "prototype-kit",
  "name": "Prototype Kit",
  "url": "https://kenney.nl/assets/prototype-kit",
  "models": [
   "coin",
   "lever-double",
   "lever-single"
  ]
 },
 {
  "slug": "furniture",
  "name": "Furniture",
  "url": "https://www.kaylousberg.com",
  "models": [
   "book-set",
   "book-single",
   "shelf-a-big",
   "shelf-a-small",
   "shelf-b-large",
   "shelf-b-large-decorated",
   "shelf-b-small",
   "table-low",
   "table-medium",
   "table-medium-long",
   "table-small"
  ]
 },
 {
  "slug": "halloween",
  "name": "Halloween",
  "url": "https://www.kaylousberg.com",
  "models": [
   "bench",
   "bone-a",
   "bone-b",
   "bone-c",
   "candle",
   "candle-melted",
   "candle-thin",
   "candle-triple",
   "floor-dirt-small",
   "lantern-hanging",
   "lantern-standing",
   "path-a",
   "path-b",
   "path-c",
   "path-d",
   "post",
   "post-lantern",
   "ribcage",
   "skull",
   "tree-dead-large",
   "tree-dead-medium",
   "tree-dead-small",
   "tree-pine-orange-large",
   "tree-pine-orange-medium",
   "tree-pine-orange-small",
   "tree-pine-yellow-large",
   "tree-pine-yellow-medium",
   "tree-pine-yellow-small"
  ]
 },
 {
  "slug": "restaurant",
  "name": "Restaurant",
  "url": "https://www.kaylousberg.com",
  "models": [
   "bowl",
   "bowl-small",
   "chair-b",
   "crate",
   "crate-ham",
   "crate-lid",
   "crate-steak",
   "cutting-board",
   "food-dinner",
   "food-ingredient-cheese",
   "food-ingredient-cheese-chopped",
   "food-ingredient-ham",
   "food-ingredient-ham-cooked",
   "food-ingredient-ham-trash",
   "food-ingredient-steak",
   "food-stew",
   "knife",
   "pan-006",
   "pan-a",
   "pan-b",
   "plate",
   "plate-small",
   "pot-a",
   "pot-b",
   "pot-large",
   "table-round-b"
  ]
 },
 {
  "slug": "fantasy-props",
  "name": "Fantasy Props",
  "url": "https://quaternius.com/",
  "models": [
   "bag",
   "barrel",
   "barrel-apples",
   "barrel-holder",
   "bench",
   "book-5",
   "book-7",
   "book-group-medium-1",
   "book-group-medium-2",
   "book-group-medium-3",
   "book-group-small-1",
   "book-group-small-2",
   "book-group-small-3",
   "book-simplified-single",
   "book-stack-1",
   "book-stack-2",
   "bottle-1",
   "bucket-wooden-1",
   "cage-small",
   "candle-1",
   "candle-2",
   "crate-metal",
   "crate-wooden",
   "key-gold",
   "key-metal",
   "mug",
   "pickaxe-bronze",
   "potion-2",
   "potion-4",
   "scroll-1",
   "scroll-2",
   "shelf-simple",
   "table-plate",
   "torch-metal",
   "vase-2",
   "vase-4",
   "vase-rubble-medium"
  ]
 },
 {
  "slug": "quaternius-nature",
  "name": "Quaternius Nature",
  "url": "https://quaternius.com/",
  "models": [
   "bush-berries-1",
   "bush-berries-2",
   "cactus-1",
   "cactus-2",
   "cactus-3",
   "cactus-4",
   "cactus-5",
   "cactus-flower-1",
   "cactus-flower-2",
   "cactus-flower-3",
   "cactus-flower-4",
   "cactus-flower-5",
   "corn-1",
   "corn-2",
   "grass",
   "grass-2",
   "grass-short",
   "lilypad",
   "log",
   "log-moss",
   "plant-1",
   "plant-2",
   "plant-3",
   "plant-4",
   "plant-5",
   "rock-1",
   "rock-2",
   "rock-3",
   "rock-4",
   "rock-5",
   "rock-6",
   "rock-7",
   "rock-moss-1",
   "rock-moss-2",
   "rock-moss-3",
   "rock-moss-4",
   "rock-moss-5",
   "rock-moss-6",
   "rock-moss-7",
   "tree-birch-dead-1",
   "tree-birch-dead-2",
   "tree-birch-dead-3",
   "tree-birch-dead-4",
   "tree-birch-dead-5",
   "tree-birch-dead-snow-1",
   "tree-birch-dead-snow-2",
   "tree-birch-dead-snow-3",
   "tree-birch-dead-snow-4",
   "tree-birch-dead-snow-5",
   "tree-common-dead-1",
   "tree-common-dead-2",
   "tree-common-dead-3",
   "tree-common-dead-4",
   "tree-common-dead-5",
   "tree-common-dead-snow-1",
   "tree-common-dead-snow-2",
   "tree-common-dead-snow-3",
   "tree-common-dead-snow-4",
   "tree-common-dead-snow-5",
   "tree-palm-1",
   "tree-palm-2",
   "tree-palm-3",
   "tree-palm-4",
   "tree-pine-1",
   "tree-pine-2",
   "tree-pine-3",
   "tree-pine-4",
   "tree-pine-5",
   "tree-stump",
   "tree-stump-moss",
   "tree-willow-dead-1",
   "tree-willow-dead-2",
   "tree-willow-dead-3",
   "tree-willow-dead-4",
   "tree-willow-dead-5",
   "wheat"
  ]
 },
 {
  "slug": "natuur",
  "name": "Natuur",
  "url": null,
  "toelichting": "De pack noemt zichzelf \"Nature Kit\" en levert geen licentiebestand en geen maker. Modelnamen, texturen en maatvoering komen overeen met de Modular Terrain Collection waar de kit Modulair Terrein uit komt; vermoedelijk dezelfde maker, zeker is dat niet. Heet hier Natuur om hem niet te verwarren met de kit Nature, die uit een andere pack komt.",
  "models": [
   "branch-1",
   "branch-2",
   "branch-3",
   "campfire-star",
   "campfire-teepee",
   "cattail-1",
   "cattail-2",
   "cattail-3",
   "cattail-4",
   "cattail-5",
   "coconut",
   "flower-balloon-1",
   "flower-balloon-2",
   "flower-balloon-3",
   "flower-bellflower-1",
   "flower-bellflower-2",
   "flower-bellflower-3",
   "flower-daisy-1",
   "flower-daisy-2",
   "flower-daisy-3",
   "flower-sunflower-1",
   "flower-sunflower-2",
   "flower-sunflower-3",
   "flower-violet-1",
   "flower-violet-2",
   "flower-violet-3",
   "grass-clump-1",
   "grass-clump-2",
   "grass-clump-3",
   "grass-clump-4",
   "grass-clump-5",
   "lamp-post",
   "log-1",
   "log-2",
   "log-3",
   "log-4",
   "log-5",
   "mountain-2",
   "mountain-3",
   "mountain-4",
   "mushroom-brown",
   "mushroom-dark-red",
   "mushroom-grey",
   "mushroom-red-spotted",
   "rock-1",
   "rock-2",
   "rock-3",
   "rock-4",
   "rock-5",
   "rock-6",
   "rock-7",
   "rock-8",
   "rock-9",
   "root-1",
   "root-2",
   "root-3",
   "root-4",
   "root-5",
   "root-6",
   "shell-layered",
   "shell-salmon",
   "shell-slate",
   "starfish-bleached",
   "starfish-salmon",
   "stepping-stone-1",
   "stepping-stone-2",
   "stepping-stone-3",
   "stepping-stone-4",
   "stump-1",
   "stump-2",
   "stump-3",
   "timber-cut-1",
   "timber-cut-2",
   "timber-cut-3",
   "timber-cut-4",
   "timber-stack-1",
   "timber-stack-2",
   "timber-whole-1",
   "tree-bare-1",
   "tree-bare-2",
   "tree-bare-3",
   "tree-bare-4",
   "tree-bare-5",
   "tree-bare-6",
   "tree-palm-1",
   "tree-palm-2",
   "tree-palm-3",
   "tree-palm-4",
   "tree-palm-5",
   "tree-palm-6",
   "tree-pine-1",
   "tree-pine-2",
   "tree-pine-3",
   "tree-pine-4",
   "tree-pine-5",
   "tree-pine-6"
  ]
 }
];
