export const BRONKITS = [
  { map: 'kenney_survival-kit', naam: 'Kenney Survival Kit', kit: 'survival-kit', formaat: 'glb' },
  { map: 'kenney_pirate-kit', naam: 'Kenney Pirate Kit', kit: 'pirate-kit', formaat: 'glb' },
  { map: 'kenney_modular-cave-kit_1.0', naam: 'Kenney Modular Cave Kit', kit: 'modular-cave-kit', formaat: 'glb' },
  { map: 'kenney_mini-forest_1.0', naam: 'Kenney Mini Forest', kit: 'mini-forest', formaat: 'glb' },
  { map: 'kenney_fantasy-town-kit_2.0', naam: 'Kenney Fantasy Town Kit', kit: 'fantasy-town-kit', formaat: 'glb' },
  { map: 'kenney_platformer-kit', naam: 'Kenney Platformer Kit', kit: 'platformer-kit', formaat: 'glb' },
  { map: 'kenney_prototypekit', naam: 'Kenney Prototype Kit', kit: 'prototype-kit', formaat: 'glb' },
  { map: 'kenney_castlekit', naam: 'Kenney Castle Kit', kit: 'castle-kit', formaat: 'glb' },
  { map: 'kenney_graveyardkit_5.0', naam: 'Kenney Graveyard Kit', kit: 'graveyard-kit', formaat: 'glb' },
  { map: 'kenney_holidaykit', naam: 'Kenney Holiday Kit', kit: null, formaat: 'glb' },
  { map: 'kenney_mini-dungeon', naam: 'Kenney Mini Dungeon', kit: 'mini-dungeon', formaat: 'glb' },

  { map: 'KayKit_Dungeon_Pack_1.1_FREE', naam: 'KayKit Dungeon Asset Pack', kit: 'dungeon', formaat: 'gltf' },
  { map: 'KayKit_Forest_Nature_Pack_1.0_FREE', naam: 'KayKit Forest Nature Pack', kit: 'forest', formaat: 'gltf' },
  { map: 'KayKit_ResourceBits_1.0_FREE', naam: 'KayKit Resource Bits', kit: 'resources', formaat: 'gltf' },
  { map: 'KayKit_RPGToolsBits_1.0_FREE', naam: 'KayKit RPG Tools Bits', kit: 'rpgtools', formaat: 'gltf' },
  // gltf holds the assembled models, obj one file per node. Reading gltf first keeps a
  // multi-part model whole; the obj pass then adds the loose parts gltf has no file for.
  { map: 'KayKit_HalloweenBits_1.0_FREE', naam: 'KayKit Halloween Bits', kit: 'halloween', formaat: 'gltf', extraFormaten: ['obj'] },
  { map: 'KayKit_Restaurant_Bits_1.0_FREE', naam: 'KayKit Restaurant Bits', kit: 'restaurant', formaat: 'gltf', extraFormaten: ['obj'] },
  { map: 'KayKit_Furniture_Bits_1.0_FREE', naam: 'KayKit Furniture Bits', kit: 'furniture', formaat: 'gltf' },
  { map: 'KayKit_Adventurers_2.0_FREE', naam: 'KayKit Adventurers', kit: 'adventurers', formaat: 'gltf' },
  { map: 'KayKit_Skeletons_1.1_FREE', naam: 'KayKit Skeletons', kit: 'skeletons', formaat: 'gltf' },

  { map: 'FantasyProps_glTF_1k', naam: 'Fantasy Props MegaKit', kit: 'fantasy-props', formaat: 'gltf' },
  { map: 'Ultimate_Nature_Pack_by_Quaternius_OBJ', naam: 'Ultimate Nature Pack', kit: 'quaternius-nature', formaat: 'obj' },
  { map: 'nature_kit', naam: 'Nature Kit', kit: 'natuur', formaat: 'obj' },
  { map: 'Modular Village', naam: 'Modular Village', kit: 'village-kit', formaat: 'obj' },
  { map: 'modular_terrain_collection', naam: 'Modular Terrain Collection', kit: 'modulair-terrein', formaat: 'obj' },

  { map: 'PropsLite_FBX', naam: 'Medieval Props Lite', kit: 'props', formaat: 'fbx' },
  { map: 'Rocks', naam: 'Rocks', kit: 'rocks', formaat: 'fbx', splitsPerMesh: true },
  { map: 'ocean', naam: 'Ocean', kit: 'onderwater-kit', formaat: 'fbx' },
  { map: 'LowPolyNaturePackLite', naam: 'Low Poly Nature Pack Lite', kit: null, formaat: 'fbx' },
  { map: 'TropicalIslandLite_FBX', naam: 'Tropical Island Lite', kit: 'tropical-island', formaat: 'fbx' },

  { map: 'KayKit_Dungeon_Pack_1.0', naam: 'KayKit Dungeon Pack 1.0', kit: 'dungeon', formaat: 'glb' },
  { map: 'KayKit_Skeletons_1.0', naam: 'KayKit Skeletons 1.0', kit: 'skeletons', formaat: 'glb' },
  { map: 'KayKit_FantasyWeaponsBits_1.0_FREE', naam: 'KayKit Fantasy Weapons Bits', kit: 'weapons', formaat: 'gltf' },
  { map: 'Tiny_Treats_House_Plants_1.0_FREE', naam: 'Tiny Treats House Plants', kit: null, formaat: 'gltf' },
  { map: 'Tiny_Treats_Baked_Goods_1.0_FREE', naam: 'Tiny Treats Baked Goods', kit: 'baked-goods', formaat: 'gltf' },
  { map: 'ClayItems_FreeTier_1.1', naam: 'Clay Items Free Tier', kit: 'clay-items', formaat: 'gltf' },
  { map: 'Updated_Modular_Dungeon_2019', naam: 'Updated Modular Dungeon', kit: 'dungeon-quaternius', formaat: 'obj' },
  { map: 'Small_Props_Pack_1', naam: 'Small Props Pack', kit: 'small-props', formaat: 'fbx' },
  { map: 'Windmill', naam: 'Windmill', kit: 'windmill', formaat: 'fbx', splitsPerMesh: true },
];
