export const GROUPS = [
  { id: 'ground', name: 'Ground & terrain', short: 'Ground', color: '#8a5d4b',
    tab: 'nature',
    description: 'The ground itself: grass, sand and dirt patches you lay a scene on, plus the landscape at large scale — `natuur/mountain-3` at a good 37 × 37 units is not a prop but a piece of terrain you build the rest on top of. Lives in the Nature tab next to the vegetation and the rocks that rise out of it. The floors you build on live with the structures: they belong with what you place, not with what lies underneath.' },
  { id: 'cave', name: 'Cave & corridors', short: 'Cave', color: '#5c4a52',
    description: 'Empty: of the modular-cave-kit only the ladder and the three floor layers still appear in the catalogue, and those are placed with the connections and the structures as an exception. The group stays because KIT_GROUPS points to it — if the corridors and rooms return, they will have a place.' },
  { id: 'cave-terrain', name: 'Cave terrain & mining', short: 'Cave terrain', color: '#7a6154',
    description: 'Empty: the cave part of the modular-terrain kit sits outside the catalogue (PO decision, see catalog/manifest.js) and the Cave tab has been removed. The group stays because the rules point to it; if those models return, they will have a place. What it held: floors, corners, sides and hills you dig a cave out of, plus the mining gear that goes with it — rails, switches, a minecart, pickaxes, wall and ceiling supports, stalagmites, hanging cables and a lamp. Also the four entrances the kit calls `Cave_Cliff`: those set a cave into a cliff face. Lives in the Cave tab next to the modular-cave-kit, but deliberately as its own group: these models do share the common colormap and so can be mixed with the other kits, and they are modular on the grid rather than whole rooms and corridors. The two don\'t fit together.' },
  { id: 'building-kit', name: 'Building kit & mills', short: 'Building kit', color: '#a8762a',
    tab: 'structures',
    description: 'Walls, roofs, pillars and mills: pieces that click together on one grid and only fit each other, plus the mills that belong to that same building set. There are three side by side — fantasy-town\'s, the village kit\'s and the dungeon kit\'s — and they don\'t fit each other; check the kit before combining two pieces. Its own tab, because hundreds of variants of the same wall and the same roof would crowd out anything sitting loose next to them in the group view.' },
  { id: 'structures', name: 'Structures & platforms', short: 'Structures', color: '#877a63',
    tab: 'structures',
    description: 'Small buildings, platforms, decks, planks, balconies and the loose walls and roofs that aren\'t part of a building kit. Also the well with its parts: the three ground pieces that go underneath and the shaft inside it, and the loose floors you build on — the survival kit\'s, with the pirate kit\'s hole included.' },
  { id: 'connections', name: 'Stairs, bridges & ladders', short: 'Stairs & bridges', color: '#c98a5a',
    tab: 'structures',
    description: 'What you use to bridge a height or a distance without building over it — useful for "word bridging".' },
  { id: 'fences', name: 'Fences, posts & gates', short: 'Fences', color: '#b08968',
    tab: 'structures',
    description: 'Marks off paths and areas, and passages that can be open or closed.' },
  { id: 'trees', name: 'Trees & palms', short: 'Trees', color: '#3da679',
    tab: 'nature',
    description: 'Loose trees and palms for forest, beach and village.' },
  { id: 'plants', name: 'Plants, grass & flowers', short: 'Plants', color: '#6cb588',
    tab: 'nature',
    description: 'Small vegetation and ground decoration.' },
  { id: 'flowers', name: 'Flowers', short: 'Flowers', color: '#e08fb0',
    tab: 'nature',
    description: 'Loose flowers: the balloon, daisy, violet, bellflower and sunflower models from natuur, the platformer kit\'s flower clusters, and the lily, rose, sunflower and tulip props from the modular-terrain kit.' },
  { id: 'grass', name: 'Grass', short: 'Grass', color: '#8fbf5c',
    tab: 'nature',
    description: 'Loose grass and grass clumps: the eight forest-kit grass models, the five grass clumps from natuur, and the four grass-clump props from the modular-terrain kit.' },
  { id: 'bare-trees', name: 'Bare trees, branches & stumps', short: 'Bare trees', color: '#8a7256',
    tab: 'nature',
    description: 'Dead and leafless trees, plus what\'s left once a tree comes down: the dead willow, birch and common trees from quaternius-nature, the bare trees from natuur and forest, the dead trees from halloween, the stumps, the loose log from quaternius-nature, the branches from natuur and modular-terrein, and the roots from natuur.' },
  { id: 'seabed', name: 'Coral, seaweed & shells', short: 'Seabed', color: '#2fa39b',
    tab: 'nature',
    description: 'Vegetation and finds from the seabed: the shells and starfish lying on the beach of the modular-terrain kit.' },
  { id: 'rocks', name: 'Rocks & stones', short: 'Rocks', color: '#9da4c4',
    tab: 'nature',
    description: 'Boulders, pebbles, gravel and loose stones for mountain, cave and coast, plus the large rock formations you use to mark off an area. Sits with the trees, plants, seabed and ground in the Nature tab — together everything that\'s already there without anyone doing anything. The rocks needed their own tab regardless: the rocks kit delivers ten rocks in two tones plus pebbles and formations, and those crowd out anything loose next to them in the object view.' },
  { id: 'furniture', name: 'Furniture & household', short: 'Furniture', color: '#c07c8a',
    description: 'The furniture: table, bench, stool and rug from the props kit, plus the beds, chairs and wall shelves from the dungeon kit. Also the two tents from the Start Camp live here — a tent is what you sleep in, same as a bed. The tableware lives with the chests and barrels, the candles with the lights, and the food with the set tables under food & cooking; the campfires belong there too, since that\'s what you cook on.' },
  { id: 'ships', name: 'Ships & sailing', short: 'Ships', color: '#474a58',
    description: 'Ships, boats, masts, oars and cannons for the Sea of Meaning.' },
  { id: 'transport', name: 'Transport', short: 'Transport', color: '#5a7a9c',
    description: 'Ways to move things and people: the carts from fantasy-town-kit and village-kit, the rowing boats from village-kit and pirate-kit, the cannons and mast from pirate-kit, and the ships and wreck from pirate-kit.' },
  { id: 'food', name: 'Food & cooking', short: 'Food', color: '#9c3f2e',
    description: 'What you prepare and what you put it on: the campfires and the firewood, the two fish from the survival kit, the roast, the leg of meat and the mushroom, the three set tables from the dungeon kit, and the tableware that goes with them — seven plates and a mug. The bare and broken tables live with the furniture, the jugs and the sack with the chests and barrels.' },
  { id: 'storage', name: 'Chests & barrels', short: 'Chests', color: '#dd9f79',
    description: 'Something to put things in: chests, barrels, crates, boxes, bottles, buckets and pots from ten kits, plus the four jugs and the sack from the props kit and the three carts you move it all with. Good as a reward or a gathering point. What\'s inside lives with the resources; the mugs and plates live with food & cooking.' },
  { id: 'assemblies', name: 'Assemblies', short: 'Assemblies', color: '#b5651d',
    description: 'Models that aren\'t one thing but a little scene: a set table, a stack of crates, a piled-up bed, a chest full of bottles, the bars and stacks from the resources kit. They\'re finished as they stand — you place them rather than build them yourself from loose pieces — and they\'re correspondingly heavy: most of the most expensive models in the collection live here. Among the loose props they give a false picture of what a prop costs, so they\'re filtered out by default — the `assembly` tag is set to exclude on open. The loose chest, table or bar lives with its own kind as normal.' },
  { id: 'resources', name: 'Resources & supplies', short: 'Resources', color: '#4f7d8c',
    description: 'The resources themselves, apart from what you put them in: chunks of ore (copper, gold, iron, silver), stones, wood, textiles, a pallet and parts from the resources kit, plus the plank stack from the survival kit. Usable as loot, currency or building stock. The bars and the piled-up stacks from that same kit live with the assemblies.' },
  { id: 'tools', name: 'Tools & weapons', short: 'Tools', color: '#6d738a',
    description: 'Axe, hammer and broom — pairable with mechanics like "word chopping". Twenty-eight strong in the rpgtools kit: anvil, file, grindstone, hammers, screwdrivers and more blacksmith and carpentry gear, plus an explorer\'s measuring and drawing kit: compass, drafting compass, magnifying glass, pencils and rope.' },
  { id: 'signs', name: 'Signs, flags & targets', short: 'Signs', color: '#ffb349',
    description: 'Signposts, banners and targets. Carriers for text and instruction.' },
  { id: 'items', name: 'Collectibles & mechanics', short: 'Items', color: '#f1976c',
    description: 'Coin, key, star and heart alongside lever, spring and lock: small loose objects you pick up or that react to an action. The village bell belongs here too, along with the coins, keys and keyrings from the dungeon kit — not collectibles, but small, loose and with a function. Use sparingly, not a points economy.' },
  { id: 'books-scrolls', name: 'Books & scrolls', short: 'Books', color: '#a9825c',
    description: 'Reading and writing gear: loose books and book stacks/groups from fantasy-props, the rpgtools kit\'s journal (open and closed) and its rolled and empty maps, and the two scrolls from fantasy-props.' },
  { id: 'animals', name: 'Animals', short: 'Animals', color: '#3e8fd0',
    description: 'Livestock: the marine life from the underwater kit, from clownfish to whale, all rigged and animated. Currently empty — that kit sits outside the catalogue (`outsideCatalog` in catalog/manifest.js) — but the group stays, because the rules point to it and without a group those models would have nowhere to appear if they came back. The two fish from the survival kit live with food & cooking: those are meant as food.' },
  { id: 'lights', name: 'Lights & lamps', short: 'Lights', color: '#f2cb45',
    description: 'Everything that gives light, from five kits together: the street lamp and the wall lamp from the village kit, the candles from props and dungeon (loose, melted, thin, triple, lit and snuffed), the wall shelf with candles, the torches from dungeon and rpgtools, the lantern, and Taaleiland\'s own lighthouse. Handy for lighting a scene or marking a route in the dark.' },
];

export const KIT_GROUPS = {
  'modular-cave-kit': 'cave',
  resources: 'resources',
};

const BUILDING_KITS = [
  ['fantasy-town-kit', /^(wall|roof|pillar|watermill|windmill|blade)\b/],
  ['village-kit', /^(canopy|chimney|cobblestone|dirt|door|roof|stone|stucco|waterwheel|windmill|wood|window)\b/],
  ['dungeon', /^(wall|floor|ceiling|pillar|rubble|column)\b/],
];

const MODULAR_TERRAIN = [
  [/^cave-/, 'cave-terrain'],
  [/-prop-(tree|branch|stump)/, 'trees'],
  [/-prop-(cattail|coconut|flower|grass-clump|mushroom)/, 'plants'],
  [/-prop-(boulder|rock|stepping-stones)/, 'rocks'],
  [/-prop-fence-/, 'fences'],
  [/-prop-camp-(campfire|wood-pile)/, 'food'],
  [/-prop-bridge-/, 'connections'],
  [/-prop-(docks|ruins-pillar)/, 'structures'],
  [/-prop-(shell|starfish)/, 'seabed'],
  [/-prop-treasure-chest/, 'storage'],
  [/-terrain-|^mountain-/, 'ground'],
];

const ASSEMBLIES = new Set([
  'dungeon/barrel-large-decorated', 'dungeon/barrel-small-stack', 'dungeon/bed-decorated',
  'dungeon/box-small-decorated', 'dungeon/box-stacked', 'dungeon/chest-gold',
  'dungeon/crates-stacked', 'dungeon/keg-decorated', 'dungeon/table-long-decorated-a',
  'dungeon/table-long-decorated-c', 'dungeon/table-medium-decorated-a',
  'dungeon/table-small-decorated-a', 'dungeon/table-small-decorated-b', 'dungeon/wall-shelves',
  'fantasy-props/barrel-apples',
  'pirate-kit/crate-bottles',
  'restaurant/crate-ham', 'restaurant/crate-steak', 'restaurant/food-dinner',
  'resources/copper-bars', 'resources/copper-bars-stack-large',
  'resources/copper-bars-stack-medium', 'resources/copper-bars-stack-small',
  'resources/gold-bars', 'resources/gold-bars-stack-large', 'resources/gold-bars-stack-medium',
  'resources/gold-bars-stack-small', 'resources/silver-bars',
  'resources/silver-bars-stack-large', 'resources/silver-bars-stack-medium',
  'resources/silver-bars-stack-small',
]);

const exceptions = {
  'platformer-kit/arrow': 'signs',
  'platformer-kit/arrows': 'signs',
  'platformer-kit/lock': 'items',
  'fantasy-town-kit/wheel': 'tools',
  'survival-kit/resource-stone': 'rocks',
  'survival-kit/resource-stone-large': 'rocks',
  'pirate-kit/hole': 'structures',
  'mini-forest/target': 'signs',
  'modular-cave-kit/template-floor-layer': 'structures',
  'modular-cave-kit/template-floor-layer-hole': 'structures',
  'modular-cave-kit/template-floor-layer-raised': 'structures',
  'modular-cave-kit/ladder': 'connections',
  'natuur/starfish-bleached': 'seabed',
  'natuur/starfish-salmon': 'seabed',
  'halloween/post-lantern': 'lights',
  'fantasy-props/table-plate': 'food',
  'restaurant/pot-a': 'food',
  'restaurant/pot-b': 'food',
  'restaurant/pot-large': 'food',
  'restaurant/knife': 'tools',
  'survival-kit/tree-log': 'resources',
  'survival-kit/tree-log-small': 'resources',
  'natuur/log-1': 'resources',
  'natuur/log-2': 'resources',
  'natuur/log-3': 'resources',
  'natuur/log-4': 'resources',
  'natuur/log-5': 'resources',
  'pirate-kit/platform-planks': 'resources',
  'props/firewood-a': 'resources',
  'modulair-terrein/hilly-prop-camp-wood-pile': 'resources',
  'natuur/timber-stack-1': 'resources',
  'natuur/timber-stack-2': 'resources',
  'resources/wood-planks-stack-small': 'resources',
  'resources/wood-planks-stack-medium': 'resources',
  'resources/wood-planks-stack-large': 'resources',
  'resources/wood-log-stack': 'resources',
  'resources/stone-bricks-stack-small': 'resources',
  'resources/stone-bricks-stack-medium': 'resources',
  'resources/stone-bricks-stack-large': 'resources',
  'resources/iron-bars-stack-small': 'resources',
  'resources/iron-bars': 'resources',
  'resources/iron-bars-stack-large': 'resources',
  'resources/iron-bars-stack-medium': 'resources',
  'platformer-kit/stones': 'resources',
  'fantasy-props/potion-4': 'storage',
  'fantasy-props/potion-2': 'storage',
  'natuur/mushroom-dark-red': 'plants',
  'natuur/mushroom-brown': 'plants',
  'props/mushroom-a': 'plants',
  'natuur/mushroom-red-spotted': 'plants',
  'natuur/mushroom-grey': 'plants',
  'fantasy-props/book-stack-2': 'books-scrolls',
  'fantasy-props/book-group-medium-2': 'books-scrolls',
  'fantasy-props/book-group-medium-1': 'books-scrolls',
  'fantasy-props/book-stack-1': 'books-scrolls',
  'fantasy-props/book-group-small-3': 'books-scrolls',
  'fantasy-props/book-group-small-2': 'books-scrolls',
  'fantasy-props/book-group-small-1': 'books-scrolls',
  'fantasy-props/book-group-medium-3': 'books-scrolls',
  'fantasy-props/book-5': 'books-scrolls',
  'fantasy-props/book-7': 'books-scrolls',
  'fantasy-props/book-simplified-single': 'books-scrolls',
  'rpgtools/journal-closed': 'books-scrolls',
  'rpgtools/journal-open': 'books-scrolls',
  'rpgtools/map-rolled': 'books-scrolls',
  'rpgtools/map-empty': 'books-scrolls',
  'fantasy-props/scroll-2': 'books-scrolls',
  'fantasy-props/scroll-1': 'books-scrolls',
  'natuur/flower-balloon-1': 'flowers',
  'natuur/flower-balloon-2': 'flowers',
  'natuur/flower-daisy-2': 'flowers',
  'natuur/flower-daisy-3': 'flowers',
  'natuur/flower-violet-3': 'flowers',
  'natuur/flower-violet-2': 'flowers',
  'natuur/flower-violet-1': 'flowers',
  'natuur/flower-daisy-1': 'flowers',
  'natuur/flower-balloon-3': 'flowers',
  'natuur/flower-bellflower-3': 'flowers',
  'natuur/flower-sunflower-3': 'flowers',
  'natuur/flower-sunflower-2': 'flowers',
  'natuur/flower-bellflower-2': 'flowers',
  'natuur/flower-bellflower-1': 'flowers',
  'natuur/flower-sunflower-1': 'flowers',
  'platformer-kit/flowers': 'flowers',
  'platformer-kit/flowers-tall': 'flowers',
  'modulair-terrein/hilly-prop-flower-lily-blue': 'flowers',
  'modulair-terrein/hilly-prop-flower-lily-pink': 'flowers',
  'modulair-terrein/hilly-prop-flower-rose': 'flowers',
  'modulair-terrein/hilly-prop-flower-sunflower': 'flowers',
  'modulair-terrein/hilly-prop-flower-tulip': 'flowers',
  'forest/grass-1-a': 'grass',
  'forest/grass-1-b': 'grass',
  'forest/grass-1-c': 'grass',
  'forest/grass-1-d': 'grass',
  'forest/grass-2-a': 'grass',
  'forest/grass-2-b': 'grass',
  'forest/grass-2-c': 'grass',
  'forest/grass-2-d': 'grass',
  'natuur/grass-clump-1': 'grass',
  'natuur/grass-clump-2': 'grass',
  'natuur/grass-clump-3': 'grass',
  'natuur/grass-clump-4': 'grass',
  'natuur/grass-clump-5': 'grass',
  'modulair-terrein/hilly-prop-grass-clump-a': 'grass',
  'modulair-terrein/hilly-prop-grass-clump-b': 'grass',
  'modulair-terrein/hilly-prop-grass-clump-c': 'grass',
  'modulair-terrein/hilly-prop-grass-clump-d': 'grass',
  'quaternius-nature/tree-willow-dead-1': 'bare-trees',
  'quaternius-nature/tree-willow-dead-2': 'bare-trees',
  'quaternius-nature/tree-willow-dead-3': 'bare-trees',
  'quaternius-nature/tree-willow-dead-4': 'bare-trees',
  'quaternius-nature/tree-willow-dead-5': 'bare-trees',
  'natuur/tree-bare-1': 'bare-trees',
  'forest/tree-bare-1-a': 'bare-trees',
  'forest/tree-bare-1-b': 'bare-trees',
  'forest/tree-bare-1-c': 'bare-trees',
  'natuur/tree-bare-5': 'bare-trees',
  'quaternius-nature/tree-birch-dead-5': 'bare-trees',
  'halloween/tree-dead-large': 'bare-trees',
  'quaternius-nature/tree-common-dead-5': 'bare-trees',
  'quaternius-nature/tree-birch-dead-4': 'bare-trees',
  'natuur/tree-bare-4': 'bare-trees',
  'natuur/tree-bare-2': 'bare-trees',
  'natuur/tree-bare-3': 'bare-trees',
  'quaternius-nature/tree-birch-dead-3': 'bare-trees',
  'quaternius-nature/tree-common-dead-4': 'bare-trees',
  'forest/tree-bare-2-c': 'bare-trees',
  'quaternius-nature/tree-birch-dead-2': 'bare-trees',
  'quaternius-nature/tree-common-dead-3': 'bare-trees',
  'forest/tree-bare-2-b': 'bare-trees',
  'quaternius-nature/tree-birch-dead-1': 'bare-trees',
  'quaternius-nature/tree-common-dead-2': 'bare-trees',
  'forest/tree-bare-2-a': 'bare-trees',
  'natuur/tree-bare-6': 'bare-trees',
  'quaternius-nature/tree-common-dead-1': 'bare-trees',
  'halloween/tree-dead-medium': 'bare-trees',
  'halloween/tree-dead-small': 'bare-trees',
  'natuur/stump-1': 'bare-trees',
  'natuur/stump-2': 'bare-trees',
  'natuur/stump-3': 'bare-trees',
  'modulair-terrein/hilly-prop-stump': 'bare-trees',
  'quaternius-nature/log': 'bare-trees',
  'natuur/branch-1': 'bare-trees',
  'natuur/branch-2': 'bare-trees',
  'natuur/branch-3': 'bare-trees',
  'modulair-terrein/hilly-prop-branch-a': 'bare-trees',
  'modulair-terrein/hilly-prop-branch-b': 'bare-trees',
  'modulair-terrein/hilly-prop-branch-c': 'bare-trees',
  'natuur/root-1': 'bare-trees',
  'natuur/root-2': 'bare-trees',
  'natuur/root-3': 'bare-trees',
  'natuur/root-4': 'bare-trees',
  'natuur/root-5': 'bare-trees',
  'natuur/root-6': 'bare-trees',
  'fantasy-town-kit/cart-high': 'transport',
  'village-kit/cart-a': 'transport',
  'fantasy-town-kit/cart': 'transport',
  'village-kit/boat-a': 'transport',
  'village-kit/boat-b': 'transport',
  'village-kit/boat-oars-a': 'transport',
  'village-kit/boat-oars-b': 'transport',
  'pirate-kit/boat-row-small': 'transport',
  'pirate-kit/boat-row-large': 'transport',
  'pirate-kit/cannon': 'transport',
  'pirate-kit/cannon-ball': 'transport',
  'pirate-kit/cannon-mobile': 'transport',
  'pirate-kit/mast': 'transport',
  'pirate-kit/ship-ghost': 'transport',
  'pirate-kit/ship-large': 'transport',
  'pirate-kit/ship-pirate-small': 'transport',
  'pirate-kit/ship-wreck': 'transport',
};

const rules = [
  [/^(corridor|room|template)\b/, 'cave'],
  [/^(crab|dolphin|eel|lobster|octopus|orca|penguin|seal|shark|squid|starfish|stingray|turtle|whale)\b/, 'animals'],
  [/^(coral|seaweed|shell|sand-dollar)\b/, 'seabed'],
  [/^(campfire|fire|firewood|plate|roast|meat|mushroom|cup|bowl|chalice|food|pan|mug|cutting-board)\b|^(fish|fish-large|table-long-decorated-a|table-long-decorated-c|table-medium-decorated-a)$/, 'food'],
  [/^tent\b|^tent-/, 'furniture'],
  [/^(ship|boat|mast|cannon)\b|^ship-|^boat-|^mast-|^cannon-/, 'ships'],
  [/^fish/, 'animals'],
  [/^(tool|workbench)-|^workbench$|^broom$/, 'tools'],
  [/^(anvil|axe|chisel|compass|drafting-compass|file|grindstone|hammer|handdrill|handplane|knife|magnifying-glass|mallet|nail|pencil|pickaxe|rope|saw|scissors|screw|screwdriver|shovel|tongs|trowel|wrench)\b/, 'tools'],
  [/^(journal|map)\b/, 'items'],
  [/^(sign|signpost|banner|flag)\b|^sign-|^signpost-|^banner-|^flag-/, 'signs'],
  [/^(lamp|lantern|torch|candle|lighthouse)\b|^shelf-small-candles$/, 'lights'],
  [/^(star|heart|spring|lock)$|^(bell|coin|keyring|key|lever|book|scroll|potion|bone|ribcage|skull)\b/, 'items'],
  [/^(table|bench|stool|carpet|bed|chair|shelf|shelves)\b/, 'furniture'],
  [/^(resource|timber)\b/, 'resources'],
  [/^(chest|barrel|box|crate|crates|pot|bucket|bottle|jug|bag|cart|keg|trunk|cage|vase)\b|-bottles$/, 'storage'],
  [/^(stairs|ladder|bridge|balloon)\b/, 'connections'],
  [/^(fence|poles|gate|post)\b/, 'fences'],
  [/^(tree|palm|branch|pine|willow|log|root|stump)\b/, 'trees'],
  [/^(plant|grass|flowers?|mushrooms|bush|cactus|corn|wheat|lilypad|cattail|coconut)\b/, 'plants'],
  [/^(rock|rocks|rockform|rockwall|stone|stones|stepping-stone|pebbles|debris)\b/, 'rocks'],
  [/^(patch|dirt|mountain|hills|snow|path)\b/, 'ground'],
  [/^(floor|hole)\b/, 'structures'],
  [/^(wall|roof|building|structure|platform|pillar|column|balcony|overhang|planks?|tower|wood|watermill|windmill|fountain|well)\b/, 'structures'],
];

export function determineGroup(kit, model) {
  const key = `${kit}/${model}`;
  if (ASSEMBLIES.has(key)) return 'assemblies';
  if (exceptions[key]) return exceptions[key];
  if (KIT_GROUPS[kit]) return KIT_GROUPS[kit];
  for (const [kitPakket, pattern] of BUILDING_KITS) {
    if (kit === kitPakket && pattern.test(model)) return 'building-kit';
  }
  if (kit === 'modulair-terrein') {
    for (const [pattern, group] of MODULAR_TERRAIN) {
      if (pattern.test(model)) return group;
    }
  }
  for (const [pattern, group] of rules) {
    if (pattern.test(model)) return group;
  }
  return 'other';
}
