/* generated from the downloaded Kenney kits — model lists per kit */
window.KENNEY_KITS = [
 {
  "slug": "survival-kit",
  "name": "Survival Kit",
  "url": "https://kenney.nl/assets/survival-kit",
  "models": [
   "bottle",
   "bottle-large",
   "bucket",
   "campfire-fishing-stand",
   "campfire-pit",
   "campfire-stand",
   "chest",
   "fence",
   "fence-doorway",
   "fence-fortified",
   "fish",
   "fish-large",
   "floor",
   "floor-hole",
   "floor-old",
   "grass",
   "grass-large",
   "patch-grass",
   "patch-grass-large",
   "resource-planks",
   "resource-stone",
   "resource-stone-large",
   "rock-a",
   "rock-b",
   "rock-c",
   "rock-flat",
   "rock-flat-grass",
   "rock-sand-a",
   "rock-sand-b",
   "rock-sand-c",
   "signpost",
   "signpost-single",
   "structure",
   "structure-canvas",
   "structure-floor",
   "structure-roof",
   "tent",
   "tent-canvas",
   "tool-axe",
   "tool-hammer",
   "tool-hoe",
   "tool-pickaxe",
   "tool-shovel",
   "tree",
   "tree-log",
   "tree-log-small",
   "tree-tall",
   "workbench",
   "workbench-anvil",
   "workbench-grind"
  ]
 },
 {
  "slug": "pirate-kit",
  "name": "Pirate Kit",
  "url": "https://kenney.nl/assets/pirate-kit",
  "models": [
   "boat-row-large",
   "boat-row-small",
   "bottle",
   "bottle-large",
   "cannon",
   "cannon-ball",
   "cannon-mobile",
   "chest",
   "crate",
   "crate-bottles",
   "flag",
   "flag-high",
   "grass",
   "grass-plant",
   "hole",
   "mast",
   "mast-ropes",
   "palm-bend",
   "palm-detailed-bend",
   "palm-detailed-straight",
   "palm-straight",
   "patch-grass",
   "patch-grass-foliage",
   "patch-sand",
   "patch-sand-foliage",
   "platform",
   "platform-planks",
   "rocks-a",
   "rocks-b",
   "rocks-c",
   "rocks-sand-a",
   "rocks-sand-b",
   "rocks-sand-c",
   "ship-ghost",
   "ship-large",
   "ship-medium",
   "ship-pirate-large",
   "ship-pirate-medium",
   "ship-pirate-small",
   "ship-small",
   "ship-wreck",
   "structure",
   "structure-fence",
   "structure-fence-sides",
   "structure-platform",
   "structure-platform-dock",
   "structure-platform-dock-small",
   "structure-platform-small",
   "structure-roof",
   "tool-paddle"
  ]
 },
 {
  "slug": "modular-cave-kit",
  "name": "Modular Cave Kit",
  "url": "https://kenney.nl/assets/modular-cave-kit",
  /* Eigen tabblad: eigen texture-atlas, deelt geen kleur met de andere kits. */
  "tabblad": "grot",
  "toelichting": "Staat op zichzelf: eigen texture-atlas en eigen kleuren, gedeeld met geen enkele andere kit. Daarom een eigen tabblad — deze modellen zijn niet uitwisselbaar met die van de andere kits.",
  "models": [
   "corridor",
   "corridor-corner",
   "corridor-end",
   "corridor-intersection",
   "corridor-junction",
   "corridor-transition",
   "corridor-wide",
   "corridor-wide-corner",
   "corridor-wide-end",
   "corridor-wide-intersection",
   "corridor-wide-junction",
   "gate",
   "gate-metal-bars",
   "gate-overhang",
   "gate-rock",
   "ladder",
   "room-corner",
   "room-large",
   "room-large-variation",
   "room-small",
   "room-small-variation",
   "room-wide",
   "room-wide-variation",
   "stairs",
   "stairs-wide",
   "template-corner",
   "template-detail",
   "template-floor",
   "template-floor-big",
   "template-floor-detail",
   "template-floor-detail-a",
   "template-floor-layer",
   "template-floor-layer-hole",
   "template-floor-layer-raised",
   "template-wall",
   "template-wall-corner",
   "template-wall-detail-a",
   "template-wall-half",
   "template-wall-stairs",
   "template-wall-top"
  ]
 },
 {
  "slug": "mini-forest",
  "name": "Mini Forest",
  "url": "https://kenney.nl/assets/mini-forest",
  "models": [
   "bridge",
   "building-platform",
   "building-roof",
   "building-structure",
   "fence",
   "flag",
   "ladder",
   "patch-dirt",
   "patch-grass",
   "plant",
   "rocks-high",
   "rocks-low",
   "rocks-ramp",
   "stones",
   "target",
   "tent",
   "tree",
   "tree-high",
   "weapon-arrow",
   "weapon-bow"
  ]
 },
 {
  "slug": "fantasy-town-kit",
  "name": "Fantasy Town Kit",
  "url": "https://kenney.nl/assets/fantasy-town-kit",
  "models": [
   "balcony-wall",
   "balcony-wall-fence",
   "banner-green",
   "banner-red",
   "blade",
   "cart",
   "cart-high",
   "fence",
   "fence-broken",
   "fence-curved",
   "fence-gate",
   "overhang",
   "pillar-wood",
   "planks",
   "planks-half",
   "planks-opening",
   "poles",
   "poles-horizontal",
   "rock-large",
   "rock-small",
   "rock-wide",
   "roof-corner",
   "roof-corner-inner",
   "roof-corner-round",
   "roof-flat",
   "roof-gable-detail",
   "roof-gable-end",
   "roof-gable-top",
   "roof-left",
   "roof-point",
   "roof-right",
   "roof-window",
   "stairs-stone-corner",
   "stairs-stone-round",
   "stairs-wide-wood",
   "stairs-wide-wood-handrail",
   "stairs-wood",
   "stairs-wood-handrail",
   "tree",
   "tree-crooked",
   "tree-high",
   "tree-high-crooked",
   "tree-high-round",
   "wall-wood",
   "wall-wood-arch",
   "wall-wood-arch-top",
   "wall-wood-block",
   "wall-wood-block-half",
   "wall-wood-broken",
   "wall-wood-corner",
   "wall-wood-corner-diagonal",
   "wall-wood-corner-diagonal-half",
   "wall-wood-corner-edge",
   "wall-wood-detail-cross",
   "wall-wood-detail-diagonal",
   "wall-wood-detail-horizontal",
   "wall-wood-diagonal",
   "wall-wood-door",
   "wall-wood-doorway-base",
   "wall-wood-doorway-square",
   "wall-wood-doorway-square-wide-curved",
   "wall-wood-half",
   "wall-wood-side",
   "wall-wood-window-glass",
   "wall-wood-window-round",
   "wall-wood-window-shutters",
   "watermill",
   "watermill-wide",
   "wheel",
   "windmill"
  ]
 },
 {
  "slug": "platformer-kit",
  "name": "Platformer Kit",
  "url": "https://kenney.nl/assets/platformer-kit",
  "models": [
   "arrow",
   "arrows",
   "crate",
   "crate-strong",
   "fence-broken",
   "fence-corner",
   "fence-corner-curved",
   "fence-low-broken",
   "fence-low-corner",
   "fence-low-corner-curved",
   "fence-low-straight",
   "fence-rope",
   "fence-straight",
   "flowers",
   "flowers-tall",
   "grass",
   "heart",
   "ladder",
   "ladder-broken",
   "ladder-long",
   "lever",
   "lock",
   "mushrooms",
   "plant",
   "platform",
   "platform-fortified",
   "platform-overhang",
   "platform-ramp",
   "poles",
   "rocks",
   "sign",
   "spring",
   "star",
   "stones",
   "tree-pine",
   "tree-pine-small"
  ]
 },
 {
  "slug": "mini-dungeon",
  "name": "Mini Dungeon",
  "url": "https://kenney.nl/assets/mini-dungeon",
  "models": [
   "banner",
   "barrel",
   "chest",
   "coin",
   "column",
   "dirt",
   "floor",
   "floor-detail",
   "gate",
   "key",
   "pot",
   "rocks",
   "stairs",
   "stones",
   "trap",
   "wall",
   "wall-half",
   "wall-narrow",
   "wall-opening",
   "wood-structure",
   "wood-support"
  ]
 },
 {
  /* geen Kenney-kit: Quaternius, zie kits/onderwater-kit/LICENSE.txt */
  "slug": "onderwater-kit",
  "name": "Onderwater",
  "url": "https://quaternius.com/",
  /* Eigen tabblad: geen colormap maar eigen materiaalkleuren, en geanimeerd. */
  "tabblad": "zee",
  /* Twee herkomsten in één map, dus de kit kan niet in z'n geheel CC0 heten. */
  "licentieLabel": "CC0, behalve orca en orca-calf",
  "toelichting": "Staat op zichzelf: eigen materiaalkleuren in plaats van de gedeelde colormap. De dieren zijn gerigd en dragen hun eigen animaties — de enige geanimeerde modellen in de catalogus. Het grootste deel is een pack van Quaternius, ingeladen op een kwart van de oorspronkelijke maat zodat het op hetzelfde raster past als de rest; orca en orca-calf zijn eigen assets die hier op kleur en animatie thuishoren.",
  "models": [
   "coral-a",
   "coral-b",
   "coral-c",
   "coral-d",
   "coral-e",
   "coral-f",
   "coral-g",
   "crab",
   "dolphin",
   "eel",
   "fish-brown",
   "fish-clown",
   "fish-dory",
   "fish-tuna",
   "lobster",
   "octopus",
   /* geen Quaternius: eigen assets, zie kits/onderwater-kit/LICENSE.txt */
   "orca",
   "orca-calf",
   "penguin",
   "rock-a",
   "rock-b",
   "rock-c",
   "rock-d",
   "rock-e",
   "rock-f",
   "rock-g",
   "rock-h",
   "rock-i",
   "rock-j",
   "rock-k",
   "sand-dollar",
   "seal",
   "seaweed-a",
   "seaweed-b",
   "seaweed-c",
   "shark",
   "shark-hammerhead",
   "shell-clam",
   "shell-scallop",
   "shell-spiral",
   "squid",
   "starfish",
   "stingray",
   "turtle",
   "whale"
  ]
 },
 {
  /* geen Kenney-kit: eigen assets, zie kits/taalei-kit/LICENSE.txt */
  "slug": "taalei-kit",
  "name": "Taalei Kit",
  "url": null,
  "models": [
   "balloon",
   "lighthouse"
  ]
 },
 {
  /* geen Kenney-kit: Low Poly Nature Pack (Lite), zie kits/nature/LICENSE.txt.
     De pack kwam zonder licentiebestand en zonder packpagina binnen; daarom
     geen url. Geen eigen tabblad: de modellen zijn omgezet naar de gedeelde
     colormap en horen dus gewoon tussen de andere kits. */
  "slug": "nature",
  "name": "Nature",
  "url": null,
  "models": [
   "branch-a",
   "mountain-a",
   "tree-dead"
  ]
 },
 {
  /* geen Kenney-kit: Tropical Island Pack (Lite), zie kits/tropical/LICENSE.txt.
     Ook deze pack kwam zonder licentiebestand en zonder packpagina binnen.
     `chest-a` staat open en `chest-b` dicht; de pack noemt ze `Chest_01` en
     `Chest_01_2` en zegt daar zelf niets over. */
  "slug": "tropical",
  "name": "Tropical",
  "url": null,
  "models": [
   "barrel-a",
   "chest-a",
   "chest-b",
   "palm-a",
   "pier-a",
   "plank-a",
   "plant-a"
  ]
 },
 {
  /* geen Kenney-kit: Medieval Props (Lite), zie kits/props/LICENSE.txt. Ook
     deze pack kwam zonder licentiebestand en zonder packpagina binnen.
     28 van de 48 modellen zijn ingeladen. Zes namen zeggen in de pack niet wat
     het model is; die heten hier naar wat ze zijn — zie tools/importeer-props.mjs. */
  "slug": "props",
  "name": "Props",
  "url": null,
  "models": [
   "bag-a",
   "barrel-a",
   "bench-a",
   "bottle-a",
   "bottle-b",
   "bottle-c",
   "box-a",
   "bucket-a",
   "bucket-b",
   "candle-a",
   "candle-b",
   "carpet-a",
   "cup-a",
   "fire-a",
   "firewood-a",
   "jug-a",
   "jug-b",
   "jug-c",
   "jug-d",
   "meat-leg-a",
   "mushroom-a",
   "plate-a",
   "plate-b",
   "plate-c",
   "roast-a",
   "stairs-a",
   "stool-a",
   "table-a"
  ]
 },
 {
  /* geen Kenney-kit: Rocks-pack, zie kits/rocks/LICENSE.txt. Kwam als één .fbx
     met 117 meshes binnen, zonder licentiebestand en zonder packpagina.
     Elk model bestaat in drie tinten; alleen `.medium` is ingeladen. De rotsen
     en kiezels zitten er wél twee keer in — `natural`/`cave` en `dirt`/`cave`
     zijn dezelfde vorm in een andere steensoort. */
  "slug": "rocks",
  "name": "Rocks",
  "url": null,
  "models": [
   "debris-a",
   "debris-b",
   "pebbles-cave-a",
   "pebbles-cave-b",
   "pebbles-cave-c",
   "pebbles-cave-d",
   "pebbles-dirt-a",
   "pebbles-dirt-b",
   "pebbles-dirt-c",
   "pebbles-dirt-d",
   "rock-cave-a",
   "rock-cave-b",
   "rock-cave-c",
   "rock-cave-d",
   "rock-cave-e",
   "rock-cave-f",
   "rock-cave-g",
   "rock-cave-h",
   "rock-cave-i",
   "rock-cave-j",
   "rock-natural-a",
   "rock-natural-b",
   "rock-natural-c",
   "rock-natural-d",
   "rock-natural-e",
   "rock-natural-f",
   "rock-natural-g",
   "rock-natural-h",
   "rock-natural-i",
   "rock-natural-j",
   "rockform-arch",
   "rockform-column",
   "rockform-corner-hard",
   "rockform-corner-soft",
   "rockform-wall-long",
   "rockform-wall-short-a",
   "rockform-wall-short-b",
   "rockwall-corner",
   "rockwall-straight"
  ]
 }
];
