// Laadt 96 modellen uit "Nature Kit" in als kits/workfiles/natuur.
//
// Aanroepen met het pad naar de uitgepakte pack:
//   node tools/importeer-natuur.mjs <pack>/Nature Kit/models
//
// Wat er gebeurt en waarom staat in kits/workfiles/natuur/LICENSE.txt.

import { importeerKit } from './importeer/kit.mjs';

const MODELLEN = [
  ['Branch_1',             'branch-1'],
  ['Branch_2',             'branch-2'],
  ['Branch_3',             'branch-3'],
  ['Campfire_Star',        'campfire-star'],
  ['Campfire_Teepee',      'campfire-teepee'],
  ['Cattail_1',            'cattail-1'],
  ['Cattail_2',            'cattail-2'],
  ['Cattail_3',            'cattail-3'],
  ['Cattail_4',            'cattail-4'],
  ['Cattail_5',            'cattail-5'],
  ['Coconut',              'coconut'],
  ['Flower_Balloon_1',     'flower-balloon-1'],
  ['Flower_Balloon_2',     'flower-balloon-2'],
  ['Flower_Balloon_3',     'flower-balloon-3'],
  ['Flower_Bellflower_1',  'flower-bellflower-1'],
  ['Flower_Bellflower_2',  'flower-bellflower-2'],
  ['Flower_Bellflower_3',  'flower-bellflower-3'],
  ['Flower_Daisy_1',       'flower-daisy-1'],
  ['Flower_Daisy_2',       'flower-daisy-2'],
  ['Flower_Daisy_3',       'flower-daisy-3'],
  ['Flower_Sunflower_1',   'flower-sunflower-1'],
  ['Flower_Sunflower_2',   'flower-sunflower-2'],
  ['Flower_Sunflower_3',   'flower-sunflower-3'],
  ['Flower_Violet_1',      'flower-violet-1'],
  ['Flower_Violet_2',      'flower-violet-2'],
  ['Flower_Violet_3',      'flower-violet-3'],
  ['Grass_Clump_1',        'grass-clump-1'],
  ['Grass_Clump_2',        'grass-clump-2'],
  ['Grass_Clump_3',        'grass-clump-3'],
  ['Grass_Clump_4',        'grass-clump-4'],
  ['Grass_Clump_5',        'grass-clump-5'],
  ['Lamp_Post',            'lamp-post'],
  ['Log_1',                'log-1'],
  ['Log_2',                'log-2'],
  ['Log_3',                'log-3'],
  ['Log_4',                'log-4'],
  ['Log_5',                'log-5'],
  ['Mountain_2',           'mountain-2'],
  ['Mountain_3',           'mountain-3'],
  ['Mountain_4',           'mountain-4'],
  ['Mushroom_Brown',       'mushroom-brown'],
  ['Mushroom_Dark_Red',    'mushroom-dark-red'],
  ['Mushroom_Grey',        'mushroom-grey'],
  ['Mushroom_Red_Spotted', 'mushroom-red-spotted'],
  ['Rock_1',               'rock-1'],
  ['Rock_2',               'rock-2'],
  ['Rock_3',               'rock-3'],
  ['Rock_4',               'rock-4'],
  ['Rock_5',               'rock-5'],
  ['Rock_6',               'rock-6'],
  ['Rock_7',               'rock-7'],
  ['Rock_8',               'rock-8'],
  ['Rock_9',               'rock-9'],
  ['Root_1',               'root-1'],
  ['Root_2',               'root-2'],
  ['Root_3',               'root-3'],
  ['Root_4',               'root-4'],
  ['Root_5',               'root-5'],
  ['Root_6',               'root-6'],
  ['Shell_Layered',        'shell-layered'],
  ['Shell_Salmon',         'shell-salmon'],
  ['Shell_Slate',          'shell-slate'],
  ['Starfish_Bleached',    'starfish-bleached'],
  ['Starfish_Salmon',      'starfish-salmon'],
  ['Stepping_Stone_1',     'stepping-stone-1'],
  ['Stepping_Stone_2',     'stepping-stone-2'],
  ['Stepping_Stone_3',     'stepping-stone-3'],
  ['Stepping_Stone_4',     'stepping-stone-4'],
  ['Stump_1',              'stump-1'],
  ['Stump_2',              'stump-2'],
  ['Stump_3',              'stump-3'],
  ['Timber_Cut_1',         'timber-cut-1'],
  ['Timber_Cut_2',         'timber-cut-2'],
  ['Timber_Cut_3',         'timber-cut-3'],
  ['Timber_Cut_4',         'timber-cut-4'],
  ['Timber_Stack_1',       'timber-stack-1'],
  ['Timber_Stack_2',       'timber-stack-2'],
  ['Timber_Whole_1',       'timber-whole-1'],
  ['Tree_Bare_1',          'tree-bare-1'],
  ['Tree_Bare_2',          'tree-bare-2'],
  ['Tree_Bare_3',          'tree-bare-3'],
  ['Tree_Bare_4',          'tree-bare-4'],
  ['Tree_Bare_5',          'tree-bare-5'],
  ['Tree_Bare_6',          'tree-bare-6'],
  ['Tree_Palm_1',          'tree-palm-1'],
  ['Tree_Palm_2',          'tree-palm-2'],
  ['Tree_Palm_3',          'tree-palm-3'],
  ['Tree_Palm_4',          'tree-palm-4'],
  ['Tree_Palm_5',          'tree-palm-5'],
  ['Tree_Palm_6',          'tree-palm-6'],
  ['Tree_Pine_1',          'tree-pine-1'],
  ['Tree_Pine_2',          'tree-pine-2'],
  ['Tree_Pine_3',          'tree-pine-3'],
];

await importeerKit({
  slug: 'natuur',
  bron: 'Nature Kit',
  generator: 'tools/importeer-natuur.mjs',
  schaal: 0.3,
  formaat: 'obj',
  bronDir: process.argv[2] ?? (() => { throw new Error('geef het pad naar de uitgepakte pack'); })(),
  modellen: MODELLEN,
});
