name: Deploy static content to Pages

on:
  push:

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          repository: Paumen/lp-sources
          path: lp-sources
          sparse-checkout: kits/reject
      - name: Place rejected models
        run: |
          rm kits/sources kits/reject
          mv lp-sources/kits/reject kits/reject
          rm -rf lp-sources
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
